// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_kubernetes_security_policy_template_v2

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KubernetesSecurityPolicyTemplateV2DataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Brief description of the template's purpose.",
				MarkdownDescription: "Brief description of the template's purpose.",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The security policy template's ID. Used to fetch a specific security policy template.",
				MarkdownDescription: "The security policy template's ID. Used to fetch a specific security policy template.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Name of the security policy template (e.g., `k8sallowedrepos`).",
				MarkdownDescription: "Name of the security policy template (e.g., `k8sallowedrepos`).",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region for which to retrieve security policy templates. Defaults to provider's `region`.",
				MarkdownDescription: "The region for which to retrieve security policy templates. Defaults to provider's `region`.",
			},
			"settings_description": schema.StringAttribute{
				Computed:            true,
				Description:         "Base64-encoded JSON schema defining the configurable parameters of the policy.",
				MarkdownDescription: "Base64-encoded JSON schema defining the configurable parameters of the policy.",
			},
			"version": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Version of the security policy template.",
				MarkdownDescription: "Version of the security policy template.",
			},
		},
		Description: "Use this data source to retrieve information about specific VKCS Kubernetes cluster security policy template.",
	}
}

type KubernetesSecurityPolicyTemplateV2Model struct {
	Description         types.String `tfsdk:"description"`
	Id                  types.String `tfsdk:"id"`
	Name                types.String `tfsdk:"name"`
	Region              types.String `tfsdk:"region"`
	SettingsDescription types.String `tfsdk:"settings_description"`
	Version             types.String `tfsdk:"version"`
}
