// Package resource_cluster contains the Plugin Framework implementation of
// vkcs_dataplatform_cluster.
//
// cluster_resource_gen.go is regenerated by the scripts/dpgen wrapper, which
// works around an upstream bug with nested-type name collisions
// (https://github.com/hashicorp/terraform-plugin-codegen-framework/issues/20).
// FIELD renames (not type renames) that the wrapper cannot infer live in
// vkcs/dataplatform/spec/dpgen-overrides.json.

//go:generate go run github.com/vk-cs/terraform-provider-vkcs/scripts/dpgen -spec ../spec/spec.json -overrides ../spec/dpgen-overrides.json -out cluster_resource_gen.go
//go:generate gofmt -w cluster_resource_gen.go
//go:generate golines -w --max-len=120 cluster_resource_gen.go

package resource_cluster
