// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_kubernetes_cluster_addon_v2

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KubernetesClusterAddonV2DataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"addon_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the addon definition.",
				MarkdownDescription: "The unique identifier of the addon definition.",
			},
			"addon_name": schema.StringAttribute{
				Computed:            true,
				Description:         "The human-readable name of the cluster addon.",
				MarkdownDescription: "The human-readable name of the cluster addon.",
			},
			"addon_version_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the addon version to install.",
				MarkdownDescription: "The ID of the addon version to install.",
			},
			"base_addon_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The human-readable name of the Kubernetes addon (e.g., `ingress-nginx`, `argocd`).",
				MarkdownDescription: "The human-readable name of the Kubernetes addon (e.g., `ingress-nginx`, `argocd`).",
			},
			"cluster_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the Kubernetes cluster where the addon is installed.",
				MarkdownDescription: "The ID of the Kubernetes cluster where the addon is installed.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The timestamp when the addon was created.",
				MarkdownDescription: "The timestamp when the addon was created.",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The unique identifier of the cluster addon.",
				MarkdownDescription: "The unique identifier of the cluster addon.",
			},
			"namespace": schema.StringAttribute{
				Computed:            true,
				Description:         "The Kubernetes namespace where the addon will be deployed.",
				MarkdownDescription: "The Kubernetes namespace where the addon will be deployed.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region in which to get the cluster addon. If omitted, the provider's `region` is used.",
				MarkdownDescription: "The region in which to get the cluster addon. If omitted, the provider's `region` is used.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The current deployment status of the addon (e.g., 'INSTALLING', 'UPDATING', 'DELETING').",
				MarkdownDescription: "The current deployment status of the addon (e.g., 'INSTALLING', 'UPDATING', 'DELETING').",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The timestamp when the addon was last updated.",
				MarkdownDescription: "The timestamp when the addon was last updated.",
			},
			"values": schema.StringAttribute{
				Computed:            true,
				Description:         "The Helm chart values for configuring the addon, typically provided as YAML string.",
				MarkdownDescription: "The Helm chart values for configuring the addon, typically provided as YAML string.",
			},
		},
		Description: "Use this data source to retrieve information about specific VKCS Kubernetes cluster addon.",
	}
}

type KubernetesClusterAddonV2Model struct {
	AddonId        types.String `tfsdk:"addon_id"`
	AddonName      types.String `tfsdk:"addon_name"`
	AddonVersionId types.String `tfsdk:"addon_version_id"`
	BaseAddonName  types.String `tfsdk:"base_addon_name"`
	ClusterId      types.String `tfsdk:"cluster_id"`
	CreatedAt      types.String `tfsdk:"created_at"`
	Id             types.String `tfsdk:"id"`
	Namespace      types.String `tfsdk:"namespace"`
	Region         types.String `tfsdk:"region"`
	Status         types.String `tfsdk:"status"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
	Values         types.String `tfsdk:"values"`
}
