// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_kubernetes_volume_types_v2

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KubernetesVolumeTypesV2DataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "A synthetic identifier set to \"volume_types\". This data source does not have a natural ID.",
				MarkdownDescription: "A synthetic identifier set to \"volume_types\". This data source does not have a natural ID.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region for which to retrieve volume types. Defaults to provider's `region`.",
				MarkdownDescription: "The region for which to retrieve volume types. Defaults to provider's `region`.",
			},
			"volume_types": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "The name of the volume type (e.g., \"ceph-hdd\", \"high-iops\").",
							MarkdownDescription: "The name of the volume type (e.g., \"ceph-hdd\", \"high-iops\").",
						},
						"zones": schema.SetAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "A set of availability zones where this volume type is available (e.g., [\"PA2\", \"MS1\", \"ME1\"]).",
							MarkdownDescription: "A set of availability zones where this volume type is available (e.g., [\"PA2\", \"MS1\", \"ME1\"]).",
						},
					},
					CustomType: VolumeTypesType{
						ObjectType: types.ObjectType{
							AttrTypes: VolumeTypesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A set of available volume types with their supported availability zones.",
				MarkdownDescription: "A set of available volume types with their supported availability zones.",
			},
		},
	}
}

type KubernetesVolumeTypesV2Model struct {
	Id          types.String `tfsdk:"id"`
	Region      types.String `tfsdk:"region"`
	VolumeTypes types.Set    `tfsdk:"volume_types"`
}

var _ basetypes.ObjectTypable = VolumeTypesType{}

type VolumeTypesType struct {
	basetypes.ObjectType
}

func (t VolumeTypesType) Equal(o attr.Type) bool {
	other, ok := o.(VolumeTypesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t VolumeTypesType) String() string {
	return "VolumeTypesType"
}

func (t VolumeTypesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	zonesAttribute, ok := attributes["zones"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zones is missing from object`)

		return nil, diags
	}

	zonesVal, ok := zonesAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zones expected to be basetypes.SetValue, was: %T`, zonesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return VolumeTypesValue{
		Name:  nameVal,
		Zones: zonesVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewVolumeTypesValueNull() VolumeTypesValue {
	return VolumeTypesValue{
		state: attr.ValueStateNull,
	}
}

func NewVolumeTypesValueUnknown() VolumeTypesValue {
	return VolumeTypesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewVolumeTypesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (VolumeTypesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing VolumeTypesValue Attribute Value",
				"While creating a VolumeTypesValue value, a missing attribute value was detected. "+
					"A VolumeTypesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VolumeTypesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid VolumeTypesValue Attribute Type",
				"While creating a VolumeTypesValue value, an invalid attribute value was detected. "+
					"A VolumeTypesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VolumeTypesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("VolumeTypesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra VolumeTypesValue Attribute Value",
				"While creating a VolumeTypesValue value, an extra attribute value was detected. "+
					"A VolumeTypesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra VolumeTypesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewVolumeTypesValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewVolumeTypesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	zonesAttribute, ok := attributes["zones"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zones is missing from object`)

		return NewVolumeTypesValueUnknown(), diags
	}

	zonesVal, ok := zonesAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zones expected to be basetypes.SetValue, was: %T`, zonesAttribute))
	}

	if diags.HasError() {
		return NewVolumeTypesValueUnknown(), diags
	}

	return VolumeTypesValue{
		Name:  nameVal,
		Zones: zonesVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewVolumeTypesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) VolumeTypesValue {
	object, diags := NewVolumeTypesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewVolumeTypesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t VolumeTypesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewVolumeTypesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewVolumeTypesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewVolumeTypesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewVolumeTypesValueMust(VolumeTypesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t VolumeTypesType) ValueType(ctx context.Context) attr.Value {
	return VolumeTypesValue{}
}

var _ basetypes.ObjectValuable = VolumeTypesValue{}

type VolumeTypesValue struct {
	Name  basetypes.StringValue `tfsdk:"name"`
	Zones basetypes.SetValue    `tfsdk:"zones"`
	state attr.ValueState
}

func (v VolumeTypesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["zones"] = basetypes.SetType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Zones.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zones"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v VolumeTypesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v VolumeTypesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v VolumeTypesValue) String() string {
	return "VolumeTypesValue"
}

func (v VolumeTypesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var zonesVal basetypes.SetValue
	switch {
	case v.Zones.IsUnknown():
		zonesVal = types.SetUnknown(types.StringType)
	case v.Zones.IsNull():
		zonesVal = types.SetNull(types.StringType)
	default:
		var d diag.Diagnostics
		zonesVal, d = types.SetValue(types.StringType, v.Zones.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"name": basetypes.StringType{},
			"zones": basetypes.SetType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"name": basetypes.StringType{},
		"zones": basetypes.SetType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name":  v.Name,
			"zones": zonesVal,
		})

	return objVal, diags
}

func (v VolumeTypesValue) Equal(o attr.Value) bool {
	other, ok := o.(VolumeTypesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Zones.Equal(other.Zones) {
		return false
	}

	return true
}

func (v VolumeTypesValue) Type(ctx context.Context) attr.Type {
	return VolumeTypesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v VolumeTypesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name": basetypes.StringType{},
		"zones": basetypes.SetType{
			ElemType: types.StringType,
		},
	}
}
