// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_kubernetes_addon_v2

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KubernetesAddonV2DataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"addon_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Identifier of the addon this version belongs to.",
				MarkdownDescription: "Identifier of the addon this version belongs to.",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Unique identifier of the addon version.",
				MarkdownDescription: "Unique identifier of the addon version.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Name of the addon.",
				MarkdownDescription: "Name of the addon.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region for which to retrieve specific addon. Defaults to provider's `region`.",
				MarkdownDescription: "The region for which to retrieve specific addon. Defaults to provider's `region`.",
			},
			"supported_kube_versions": schema.SetAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "List of supported Kubernetes versions.",
				MarkdownDescription: "List of supported Kubernetes versions.",
			},
			"values_template": schema.StringAttribute{
				Computed:            true,
				Description:         "Base64-encoded values.yaml template for the addon.",
				MarkdownDescription: "Base64-encoded values.yaml template for the addon.",
			},
			"version": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Version of the addon.",
				MarkdownDescription: "Version of the addon.",
			},
		},
		Description: "Use this data source to retrieve information about specific VKCS Kubernetes addon.",
	}
}

type KubernetesAddonV2Model struct {
	AddonId               types.String `tfsdk:"addon_id"`
	Id                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	Region                types.String `tfsdk:"region"`
	SupportedKubeVersions types.Set    `tfsdk:"supported_kube_versions"`
	ValuesTemplate        types.String `tfsdk:"values_template"`
	Version               types.String `tfsdk:"version"`
}
