// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_kubernetes_cluster_v2

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/vk-cs/terraform-provider-vkcs/vkcs/kubernetes/v2/validators"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func KubernetesClusterV2ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_address": schema.StringAttribute{
				Computed:            true,
				Description:         "URL address of cluster kubeapi-server.",
				MarkdownDescription: "URL address of cluster kubeapi-server.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"api_lb_fip": schema.StringAttribute{
				Computed:            true,
				Description:         "API LoadBalancer FIP (Floating IP). IP address field.",
				MarkdownDescription: "API LoadBalancer FIP (Floating IP). IP address field.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"api_lb_vip": schema.StringAttribute{
				Computed:            true,
				Description:         "API LoadBalancer VIP (Virtual IP). IP address field.",
				MarkdownDescription: "API LoadBalancer VIP (Virtual IP). IP address field.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"availability_zones": schema.SetAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "Availability zones of the cluster. Use 1 zone for standard cluster, 3 zones for regional cluster.",
				MarkdownDescription: "Availability zones of the cluster. Use 1 zone for standard cluster, 3 zones for regional cluster.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.RequiresReplace(),
				},
			},
			"cluster_type": schema.StringAttribute{
				Required:            true,
				Description:         "Type of the kubernetes cluster. Must be either 'standard' or 'regional'.",
				MarkdownDescription: "Type of the kubernetes cluster. Must be either 'standard' or 'regional'.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("standard", "regional"),
				},
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The time at which cluster was created.",
				MarkdownDescription: "The time at which cluster was created.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description of the cluster.",
				MarkdownDescription: "Description of the cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"enable_public_ip": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable public IP for the cluster. If true, a floating IP will be assigned to the cluster. Default false.",
				MarkdownDescription: "Enable public IP for the cluster. If true, a floating IP will be assigned to the cluster. Default false.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"external_network_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of external network.",
				MarkdownDescription: "ID of external network.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.UUIDValidator{},
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the cluster.",
				MarkdownDescription: "The ID of the cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"insecure_registries": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Addresses of registries from which you can download images without checking certificates.",
				MarkdownDescription: "Addresses of registries from which you can download images without checking certificates.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
					setplanmodifier.RequiresReplace(),
				},
				Validators: []validator.Set{
					setvalidator.ValueStringsAre(validators.InsecureRegistriesValidator{}),
				},
			},
			"k8s_config": schema.StringAttribute{
				Computed:            true,
				Description:         "Contents of the kubeconfig file. Use it to authenticate to Kubernetes cluster.",
				MarkdownDescription: "Contents of the kubeconfig file. Use it to authenticate to Kubernetes cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"labels": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Key-value pairs of labels for the cluster.",
				MarkdownDescription: "Key-value pairs of labels for the cluster.",
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.Map{
					validators.KubernetesLabelsValidator{},
				},
			},
			"loadbalancer_allowed_cidrs": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "List of CIDR blocks allowed to access the load balancer.",
				MarkdownDescription: "List of CIDR blocks allowed to access the load balancer.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.Set{
					setvalidator.ValueStringsAre(validators.CIDRValidator{}),
				},
			},
			"loadbalancer_subnet_id": schema.StringAttribute{
				Required:            true,
				Description:         "The UUID of the load balancer's subnet.",
				MarkdownDescription: "The UUID of the load balancer's subnet.",
				Validators: []validator.String{
					validators.UUIDValidator{},
				},
			},
			"master_count": schema.Int64Attribute{
				Required:            true,
				Description:         "Number of master nodes. Use 1 for standard cluster, 3 or 5 for regional cluster. Changing this creates a new cluster.",
				MarkdownDescription: "Number of master nodes. Use 1 for standard cluster, 3 or 5 for regional cluster. Changing this creates a new cluster.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"master_disks": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"size": schema.StringAttribute{
							Computed:            true,
							Description:         "Size of master disk.",
							MarkdownDescription: "Size of master disk.",
						},
						"type": schema.StringAttribute{
							Computed:            true,
							Description:         "Type of master disk.",
							MarkdownDescription: "Type of master disk.",
						},
					},
					CustomType: MasterDisksType{
						ObjectType: types.ObjectType{
							AttrTypes: MasterDisksValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "List of master disks.",
				MarkdownDescription: "List of master disks.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
			},
			"master_flavor": schema.StringAttribute{
				Required:            true,
				Description:         "Flavor UUID for master nodes. Changing this scales master nodes to the target flavor.",
				MarkdownDescription: "Flavor UUID for master nodes. Changing this scales master nodes to the target flavor.",
				Validators: []validator.String{
					validators.UUIDValidator{},
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the cluster. Should match the pattern `^[a-zA-Z][a-zA-Z0-9_.-]*$`.",
				MarkdownDescription: "The name of the cluster. Should match the pattern `^[a-zA-Z][a-zA-Z0-9_.-]*$`.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.ClusterNameValidator{},
				},
			},
			"network_id": schema.StringAttribute{
				Required:            true,
				Description:         "ID of the cluster's network. Cluster can be created only in network with SDN=sprut.",
				MarkdownDescription: "ID of the cluster's network. Cluster can be created only in network with SDN=sprut.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.UUIDValidator{},
				},
			},
			"network_plugin": schema.StringAttribute{
				Required:            true,
				Description:         "Network plugin. Must be 'calico'.",
				MarkdownDescription: "Network plugin. Must be 'calico'.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("calico"),
				},
			},
			"node_groups": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"availability_zone": schema.StringAttribute{
							Computed:            true,
							Description:         "Availability zone of node group",
							MarkdownDescription: "Availability zone of node group",
						},
						"flavor": schema.StringAttribute{
							Computed:            true,
							Description:         "Flavor of nodes in node group.",
							MarkdownDescription: "Flavor of nodes in node group.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "ID of cluster node group.",
							MarkdownDescription: "ID of cluster node group.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Name of cluster node group.",
							MarkdownDescription: "Name of cluster node group.",
						},
						"node_count": schema.Int64Attribute{
							Computed:            true,
							Description:         "Number of nodes in node group.",
							MarkdownDescription: "Number of nodes in node group.",
						},
					},
					CustomType: NodeGroupsType{
						ObjectType: types.ObjectType{
							AttrTypes: NodeGroupsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "The list of cluster node groups.",
				MarkdownDescription: "The list of cluster node groups.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
			},
			"pods_ipv4_cidr": schema.StringAttribute{
				Required:            true,
				Description:         "IPv4 CIDR for pods network.",
				MarkdownDescription: "IPv4 CIDR for pods network.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.CIDRValidator{},
				},
			},
			"project_id": schema.StringAttribute{
				Computed:            true,
				Description:         "User project ID.",
				MarkdownDescription: "User project ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Region to use for the cluster. Default is a region configured for provider.",
				MarkdownDescription: "Region to use for the cluster. Default is a region configured for provider.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Cluster current status.",
				MarkdownDescription: "Cluster current status.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"subnet_id": schema.StringAttribute{
				Required:            true,
				Description:         "ID of the cluster's subnet.",
				MarkdownDescription: "ID of the cluster's subnet.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.UUIDValidator{},
				},
			},
			"uuid": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "UUID of the cluster. If not provided, will be generated automatically.",
				MarkdownDescription: "UUID of the cluster. If not provided, will be generated automatically.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.UUIDValidator{},
				},
			},
			"version": schema.StringAttribute{
				Required:            true,
				Description:         "Kubernetes version of the cluster. Changing this upgrades a cluster.",
				MarkdownDescription: "Kubernetes version of the cluster. Changing this upgrades a cluster.",
				Validators: []validator.String{
					validators.KubernetesVersionValidator{},
				},
			},
		},
	}
}

type KubernetesClusterV2Model struct {
	ApiAddress               types.String `tfsdk:"api_address"`
	ApiLbFip                 types.String `tfsdk:"api_lb_fip"`
	ApiLbVip                 types.String `tfsdk:"api_lb_vip"`
	AvailabilityZones        types.Set    `tfsdk:"availability_zones"`
	ClusterType              types.String `tfsdk:"cluster_type"`
	CreatedAt                types.String `tfsdk:"created_at"`
	Description              types.String `tfsdk:"description"`
	EnablePublicIp           types.Bool   `tfsdk:"enable_public_ip"`
	ExternalNetworkId        types.String `tfsdk:"external_network_id"`
	Id                       types.String `tfsdk:"id"`
	InsecureRegistries       types.Set    `tfsdk:"insecure_registries"`
	K8sConfig                types.String `tfsdk:"k8s_config"`
	Labels                   types.Map    `tfsdk:"labels"`
	LoadbalancerAllowedCidrs types.Set    `tfsdk:"loadbalancer_allowed_cidrs"`
	LoadbalancerSubnetId     types.String `tfsdk:"loadbalancer_subnet_id"`
	MasterCount              types.Int64  `tfsdk:"master_count"`
	MasterDisks              types.Set    `tfsdk:"master_disks"`
	MasterFlavor             types.String `tfsdk:"master_flavor"`
	Name                     types.String `tfsdk:"name"`
	NetworkId                types.String `tfsdk:"network_id"`
	NetworkPlugin            types.String `tfsdk:"network_plugin"`
	NodeGroups               types.Set    `tfsdk:"node_groups"`
	PodsIpv4Cidr             types.String `tfsdk:"pods_ipv4_cidr"`
	ProjectId                types.String `tfsdk:"project_id"`
	Region                   types.String `tfsdk:"region"`
	Status                   types.String `tfsdk:"status"`
	SubnetId                 types.String `tfsdk:"subnet_id"`
	Uuid                     types.String `tfsdk:"uuid"`
	Version                  types.String `tfsdk:"version"`
}

var _ basetypes.ObjectTypable = MasterDisksType{}

type MasterDisksType struct {
	basetypes.ObjectType
}

func (t MasterDisksType) Equal(o attr.Type) bool {
	other, ok := o.(MasterDisksType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MasterDisksType) String() string {
	return "MasterDisksType"
}

func (t MasterDisksType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`)

		return nil, diags
	}

	sizeVal, ok := sizeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be basetypes.StringValue, was: %T`, sizeAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MasterDisksValue{
		Size:            sizeVal,
		MasterDisksType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewMasterDisksValueNull() MasterDisksValue {
	return MasterDisksValue{
		state: attr.ValueStateNull,
	}
}

func NewMasterDisksValueUnknown() MasterDisksValue {
	return MasterDisksValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMasterDisksValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MasterDisksValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MasterDisksValue Attribute Value",
				"While creating a MasterDisksValue value, a missing attribute value was detected. "+
					"A MasterDisksValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MasterDisksValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MasterDisksValue Attribute Type",
				"While creating a MasterDisksValue value, an invalid attribute value was detected. "+
					"A MasterDisksValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MasterDisksValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MasterDisksValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MasterDisksValue Attribute Value",
				"While creating a MasterDisksValue value, an extra attribute value was detected. "+
					"A MasterDisksValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MasterDisksValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMasterDisksValueUnknown(), diags
	}

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`)

		return NewMasterDisksValueUnknown(), diags
	}

	sizeVal, ok := sizeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be basetypes.StringValue, was: %T`, sizeAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewMasterDisksValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewMasterDisksValueUnknown(), diags
	}

	return MasterDisksValue{
		Size:            sizeVal,
		MasterDisksType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewMasterDisksValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MasterDisksValue {
	object, diags := NewMasterDisksValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMasterDisksValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MasterDisksType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMasterDisksValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMasterDisksValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMasterDisksValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMasterDisksValueMust(MasterDisksValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MasterDisksType) ValueType(ctx context.Context) attr.Value {
	return MasterDisksValue{}
}

var _ basetypes.ObjectValuable = MasterDisksValue{}

type MasterDisksValue struct {
	Size            basetypes.StringValue `tfsdk:"size"`
	MasterDisksType basetypes.StringValue `tfsdk:"type"`
	state           attr.ValueState
}

func (v MasterDisksValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["size"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Size.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size"] = val

		val, err = v.MasterDisksType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MasterDisksValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MasterDisksValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MasterDisksValue) String() string {
	return "MasterDisksValue"
}

func (v MasterDisksValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"size": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"size": v.Size,
			"type": v.MasterDisksType,
		})

	return objVal, diags
}

func (v MasterDisksValue) Equal(o attr.Value) bool {
	other, ok := o.(MasterDisksValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Size.Equal(other.Size) {
		return false
	}

	if !v.MasterDisksType.Equal(other.MasterDisksType) {
		return false
	}

	return true
}

func (v MasterDisksValue) Type(ctx context.Context) attr.Type {
	return MasterDisksType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MasterDisksValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"size": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = NodeGroupsType{}

type NodeGroupsType struct {
	basetypes.ObjectType
}

func (t NodeGroupsType) Equal(o attr.Type) bool {
	other, ok := o.(NodeGroupsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NodeGroupsType) String() string {
	return "NodeGroupsType"
}

func (t NodeGroupsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	availabilityZoneAttribute, ok := attributes["availability_zone"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`availability_zone is missing from object`)

		return nil, diags
	}

	availabilityZoneVal, ok := availabilityZoneAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`availability_zone expected to be basetypes.StringValue, was: %T`, availabilityZoneAttribute))
	}

	flavorAttribute, ok := attributes["flavor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`flavor is missing from object`)

		return nil, diags
	}

	flavorVal, ok := flavorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`flavor expected to be basetypes.StringValue, was: %T`, flavorAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	nodeCountAttribute, ok := attributes["node_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_count is missing from object`)

		return nil, diags
	}

	nodeCountVal, ok := nodeCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_count expected to be basetypes.Int64Value, was: %T`, nodeCountAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NodeGroupsValue{
		AvailabilityZone: availabilityZoneVal,
		Flavor:           flavorVal,
		Id:               idVal,
		Name:             nameVal,
		NodeCount:        nodeCountVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewNodeGroupsValueNull() NodeGroupsValue {
	return NodeGroupsValue{
		state: attr.ValueStateNull,
	}
}

func NewNodeGroupsValueUnknown() NodeGroupsValue {
	return NodeGroupsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNodeGroupsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NodeGroupsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NodeGroupsValue Attribute Value",
				"While creating a NodeGroupsValue value, a missing attribute value was detected. "+
					"A NodeGroupsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodeGroupsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NodeGroupsValue Attribute Type",
				"While creating a NodeGroupsValue value, an invalid attribute value was detected. "+
					"A NodeGroupsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodeGroupsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NodeGroupsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NodeGroupsValue Attribute Value",
				"While creating a NodeGroupsValue value, an extra attribute value was detected. "+
					"A NodeGroupsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NodeGroupsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNodeGroupsValueUnknown(), diags
	}

	availabilityZoneAttribute, ok := attributes["availability_zone"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`availability_zone is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	availabilityZoneVal, ok := availabilityZoneAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`availability_zone expected to be basetypes.StringValue, was: %T`, availabilityZoneAttribute))
	}

	flavorAttribute, ok := attributes["flavor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`flavor is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	flavorVal, ok := flavorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`flavor expected to be basetypes.StringValue, was: %T`, flavorAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	nodeCountAttribute, ok := attributes["node_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_count is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	nodeCountVal, ok := nodeCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_count expected to be basetypes.Int64Value, was: %T`, nodeCountAttribute))
	}

	if diags.HasError() {
		return NewNodeGroupsValueUnknown(), diags
	}

	return NodeGroupsValue{
		AvailabilityZone: availabilityZoneVal,
		Flavor:           flavorVal,
		Id:               idVal,
		Name:             nameVal,
		NodeCount:        nodeCountVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewNodeGroupsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NodeGroupsValue {
	object, diags := NewNodeGroupsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNodeGroupsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NodeGroupsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNodeGroupsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNodeGroupsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNodeGroupsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNodeGroupsValueMust(NodeGroupsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NodeGroupsType) ValueType(ctx context.Context) attr.Value {
	return NodeGroupsValue{}
}

var _ basetypes.ObjectValuable = NodeGroupsValue{}

type NodeGroupsValue struct {
	AvailabilityZone basetypes.StringValue `tfsdk:"availability_zone"`
	Flavor           basetypes.StringValue `tfsdk:"flavor"`
	Id               basetypes.StringValue `tfsdk:"id"`
	Name             basetypes.StringValue `tfsdk:"name"`
	NodeCount        basetypes.Int64Value  `tfsdk:"node_count"`
	state            attr.ValueState
}

func (v NodeGroupsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["availability_zone"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["flavor"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["node_count"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.AvailabilityZone.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["availability_zone"] = val

		val, err = v.Flavor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["flavor"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.NodeCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["node_count"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NodeGroupsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NodeGroupsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NodeGroupsValue) String() string {
	return "NodeGroupsValue"
}

func (v NodeGroupsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"availability_zone": basetypes.StringType{},
		"flavor":            basetypes.StringType{},
		"id":                basetypes.StringType{},
		"name":              basetypes.StringType{},
		"node_count":        basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"availability_zone": v.AvailabilityZone,
			"flavor":            v.Flavor,
			"id":                v.Id,
			"name":              v.Name,
			"node_count":        v.NodeCount,
		})

	return objVal, diags
}

func (v NodeGroupsValue) Equal(o attr.Value) bool {
	other, ok := o.(NodeGroupsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AvailabilityZone.Equal(other.AvailabilityZone) {
		return false
	}

	if !v.Flavor.Equal(other.Flavor) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.NodeCount.Equal(other.NodeCount) {
		return false
	}

	return true
}

func (v NodeGroupsValue) Type(ctx context.Context) attr.Type {
	return NodeGroupsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NodeGroupsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"availability_zone": basetypes.StringType{},
		"flavor":            basetypes.StringType{},
		"id":                basetypes.StringType{},
		"name":              basetypes.StringType{},
		"node_count":        basetypes.Int64Type{},
	}
}
