// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_kubernetes_security_policy_v2

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/vk-cs/terraform-provider-vkcs/vkcs/internal/framework/validators"
	"github.com/vk-cs/terraform-provider-vkcs/vkcs/kubernetes/schema_validators"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func KubernetesSecurityPolicyV2ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Kubernetes cluster. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the Kubernetes cluster. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.KSUIDValidator{},
				},
			},
			"enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Controls whether the security policy is enabled. Default is `true`. Changing this updates the security policy.",
				MarkdownDescription: "Controls whether the security policy is enabled. Default is `true`. Changing this updates the security policy.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(true),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the cluster security policy.",
				MarkdownDescription: "The ID of the cluster security policy.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"namespace": schema.StringAttribute{
				Required:            true,
				Description:         "Namespace to apply security policy to. Changing this updates the security policy.",
				MarkdownDescription: "Namespace to apply security policy to. Changing this updates the security policy.",
				Validators: []validator.String{
					schema_validators.SecPolicyNamespaceValidator{},
				},
			},
			"policy_settings": schema.StringAttribute{
				Required:            true,
				Description:         "Policy settings. Changing this updates the security policy.",
				MarkdownDescription: "Policy settings. Changing this updates the security policy.",
				Validators: []validator.String{
					schema_validators.SecPolicySettingsValidator{},
				},
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region in which to create the Kubernetes security policy. If omitted, the provider's `region` is used. **Forces replacement** on change.",
				MarkdownDescription: "The region in which to create the Kubernetes security policy. If omitted, the provider's `region` is used. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"security_policy_template_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the security policy template. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the security policy template. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.KSUIDValidator{},
				},
			},
		},
		Description: "Provides a Kubernetes cluster security policy resource. This can be used to create, modify, and delete Kubernetes cluster security policy.",
	}
}

type KubernetesSecurityPolicyV2Model struct {
	ClusterId                types.String `tfsdk:"cluster_id"`
	Enabled                  types.Bool   `tfsdk:"enabled"`
	Id                       types.String `tfsdk:"id"`
	Namespace                types.String `tfsdk:"namespace"`
	PolicySettings           types.String `tfsdk:"policy_settings"`
	Region                   types.String `tfsdk:"region"`
	SecurityPolicyTemplateId types.String `tfsdk:"security_policy_template_id"`
}
