// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_kubernetes_cluster_addon_v2

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/vk-cs/terraform-provider-vkcs/vkcs/internal/framework/validators"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func KubernetesClusterAddonV2ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"addon_id": schema.StringAttribute{
				Required:            true,
				Description:         "The unique identifier of the addon definition. **Forces replacement** on change.",
				MarkdownDescription: "The unique identifier of the addon definition. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"addon_name": schema.StringAttribute{
				Required:            true,
				Description:         "The human-readable name of the cluster addon. **Forces replacement** on change.",
				MarkdownDescription: "The human-readable name of the cluster addon. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"addon_version_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the addon version to install. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the addon version to install. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"cluster_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Kubernetes cluster where the addon will be installed. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the Kubernetes cluster where the addon will be installed. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The timestamp when the addon was created.",
				MarkdownDescription: "The timestamp when the addon was created.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the cluster addon.",
				MarkdownDescription: "The unique identifier of the cluster addon.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"namespace": schema.StringAttribute{
				Required:            true,
				Description:         "The Kubernetes namespace where the addon will be deployed. Must be a valid DNS subdomain name (e.g., 'my-namespace'). **Forces replacement** on change.",
				MarkdownDescription: "The Kubernetes namespace where the addon will be deployed. Must be a valid DNS subdomain name (e.g., 'my-namespace'). **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region in which to create the cluster addon. If omitted, the provider's `region` is used. **Forces replacement** on change.",
				MarkdownDescription: "The region in which to create the cluster addon. If omitted, the provider's `region` is used. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The current deployment status of the addon (e.g., 'INSTALLING', 'UPDATING', 'DELETING').",
				MarkdownDescription: "The current deployment status of the addon (e.g., 'INSTALLING', 'UPDATING', 'DELETING').",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"timeouts": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"create": schema.StringAttribute{
						Optional:            true,
						Description:         "Timeout for create operation (e.g., `60m`, `2h`). Default is `20m`.",
						MarkdownDescription: "Timeout for create operation (e.g., `60m`, `2h`). Default is `20m`.",
						Validators: []validator.String{
							validators.TimeDuration(),
						},
					},
					"delete": schema.StringAttribute{
						Optional:            true,
						Description:         "Timeout for delete operation (e.g., `120m`, `3h`). Default is `20m`.",
						MarkdownDescription: "Timeout for delete operation (e.g., `120m`, `3h`). Default is `20m`.",
						Validators: []validator.String{
							validators.TimeDuration(),
						},
					},
					"update": schema.StringAttribute{
						Optional:            true,
						Description:         "Timeout for update operation (e.g., `120m`, `3h`). Default is `20m`.",
						MarkdownDescription: "Timeout for update operation (e.g., `120m`, `3h`). Default is `20m`.",
						Validators: []validator.String{
							validators.TimeDuration(),
						},
					},
				},
				CustomType:          timeouts.Type{ObjectType: types.ObjectType{AttrTypes: map[string]attr.Type{"create": types.StringType, "update": types.StringType, "delete": types.StringType}}},
				Optional:            true,
				Description:         "Timeout configuration for create, update and delete operations.",
				MarkdownDescription: "Timeout configuration for create, update and delete operations.",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The timestamp when the addon was last updated.",
				MarkdownDescription: "The timestamp when the addon was last updated.",
			},
			"values": schema.StringAttribute{
				Required:            true,
				Description:         "The Helm chart values for configuring the addon, provided as YAML string.",
				MarkdownDescription: "The Helm chart values for configuring the addon, provided as YAML string.",
			},
		},
		Description: "Provides a Kubernetes cluster addon resource. This can be used to create, modify, and delete Kubernetes cluster addon.",
	}
}

type KubernetesClusterAddonV2Model struct {
	AddonId        types.String   `tfsdk:"addon_id"`
	AddonName      types.String   `tfsdk:"addon_name"`
	AddonVersionId types.String   `tfsdk:"addon_version_id"`
	ClusterId      types.String   `tfsdk:"cluster_id"`
	CreatedAt      types.String   `tfsdk:"created_at"`
	Id             types.String   `tfsdk:"id"`
	Namespace      types.String   `tfsdk:"namespace"`
	Region         types.String   `tfsdk:"region"`
	Status         types.String   `tfsdk:"status"`
	Timeouts       timeouts.Value `tfsdk:"timeouts"`
	UpdatedAt      types.String   `tfsdk:"updated_at"`
	Values         types.String   `tfsdk:"values"`
}

var _ basetypes.ObjectTypable = TimeoutsType{}

type TimeoutsType struct {
	basetypes.ObjectType
}

func (t TimeoutsType) Equal(o attr.Type) bool {
	other, ok := o.(TimeoutsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TimeoutsType) String() string {
	return "TimeoutsType"
}

func (t TimeoutsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createAttribute, ok := attributes["create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`create is missing from object`)

		return nil, diags
	}

	createVal, ok := createAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`create expected to be basetypes.StringValue, was: %T`, createAttribute))
	}

	deleteAttribute, ok := attributes["delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delete is missing from object`)

		return nil, diags
	}

	deleteVal, ok := deleteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delete expected to be basetypes.StringValue, was: %T`, deleteAttribute))
	}

	updateAttribute, ok := attributes["update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`update is missing from object`)

		return nil, diags
	}

	updateVal, ok := updateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`update expected to be basetypes.StringValue, was: %T`, updateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TimeoutsValue{
		Create: createVal,
		Delete: deleteVal,
		Update: updateVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTimeoutsValueNull() TimeoutsValue {
	return TimeoutsValue{
		state: attr.ValueStateNull,
	}
}

func NewTimeoutsValueUnknown() TimeoutsValue {
	return TimeoutsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTimeoutsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TimeoutsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TimeoutsValue Attribute Value",
				"While creating a TimeoutsValue value, a missing attribute value was detected. "+
					"A TimeoutsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TimeoutsValue Attribute Type",
				"While creating a TimeoutsValue value, an invalid attribute value was detected. "+
					"A TimeoutsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TimeoutsValue Attribute Value",
				"While creating a TimeoutsValue value, an extra attribute value was detected. "+
					"A TimeoutsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TimeoutsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTimeoutsValueUnknown(), diags
	}

	createAttribute, ok := attributes["create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`create is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	createVal, ok := createAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`create expected to be basetypes.StringValue, was: %T`, createAttribute))
	}

	deleteAttribute, ok := attributes["delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delete is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	deleteVal, ok := deleteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delete expected to be basetypes.StringValue, was: %T`, deleteAttribute))
	}

	updateAttribute, ok := attributes["update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`update is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	updateVal, ok := updateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`update expected to be basetypes.StringValue, was: %T`, updateAttribute))
	}

	if diags.HasError() {
		return NewTimeoutsValueUnknown(), diags
	}

	return TimeoutsValue{
		Create: createVal,
		Delete: deleteVal,
		Update: updateVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTimeoutsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TimeoutsValue {
	object, diags := NewTimeoutsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTimeoutsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TimeoutsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTimeoutsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTimeoutsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTimeoutsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTimeoutsValueMust(TimeoutsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TimeoutsType) ValueType(ctx context.Context) attr.Value {
	return TimeoutsValue{}
}

var _ basetypes.ObjectValuable = TimeoutsValue{}

type TimeoutsValue struct {
	Create basetypes.StringValue `tfsdk:"create"`
	Delete basetypes.StringValue `tfsdk:"delete"`
	Update basetypes.StringValue `tfsdk:"update"`
	state  attr.ValueState
}

func (v TimeoutsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["create"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["delete"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["update"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Create.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["create"] = val

		val, err = v.Delete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["delete"] = val

		val, err = v.Update.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["update"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TimeoutsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TimeoutsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TimeoutsValue) String() string {
	return "TimeoutsValue"
}

func (v TimeoutsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"create": basetypes.StringType{},
		"delete": basetypes.StringType{},
		"update": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"create": v.Create,
			"delete": v.Delete,
			"update": v.Update,
		})

	return objVal, diags
}

func (v TimeoutsValue) Equal(o attr.Value) bool {
	other, ok := o.(TimeoutsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Create.Equal(other.Create) {
		return false
	}

	if !v.Delete.Equal(other.Delete) {
		return false
	}

	if !v.Update.Equal(other.Update) {
		return false
	}

	return true
}

func (v TimeoutsValue) Type(ctx context.Context) attr.Type {
	return TimeoutsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TimeoutsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"create": basetypes.StringType{},
		"delete": basetypes.StringType{},
		"update": basetypes.StringType{},
	}
}
