// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_kubernetes_security_policy_templates_v2

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KubernetesSecurityPolicyTemplatesV2DataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "A synthetic identifier set to \"policy_templates\". This data source does not have a natural ID.",
				MarkdownDescription: "A synthetic identifier set to \"policy_templates\". This data source does not have a natural ID.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region for which to retrieve security policy templates. Defaults to provider's `region`.",
				MarkdownDescription: "The region for which to retrieve security policy templates. Defaults to provider's `region`.",
			},
			"security_policies": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"description": schema.StringAttribute{
							Computed:            true,
							Description:         "Brief description of the template's purpose.",
							MarkdownDescription: "Brief description of the template's purpose.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "Unique identifier of the security policy template.",
							MarkdownDescription: "Unique identifier of the security policy template.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Name of the security policy template (e.g., `k8sallowedrepos`).",
							MarkdownDescription: "Name of the security policy template (e.g., `k8sallowedrepos`).",
						},
						"settings_description": schema.StringAttribute{
							Computed:            true,
							Description:         "Base64-encoded JSON schema defining the configurable parameters of the policy.",
							MarkdownDescription: "Base64-encoded JSON schema defining the configurable parameters of the policy.",
						},
						"version": schema.StringAttribute{
							Computed:            true,
							Description:         "Version of the security policy template.",
							MarkdownDescription: "Version of the security policy template.",
						},
					},
					CustomType: SecurityPoliciesType{
						ObjectType: types.ObjectType{
							AttrTypes: SecurityPoliciesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A set of available security policy templates. Each template contains an `id`, `name`, `description`, `settings_description`, and `version`.",
				MarkdownDescription: "A set of available security policy templates. Each template contains an `id`, `name`, `description`, `settings_description`, and `version`.",
			},
		},
		Description: "Use this data source to retrieve information about available VKCS Kubernetes cluster security policy templates.",
	}
}

type KubernetesSecurityPolicyTemplatesV2Model struct {
	Id               types.String `tfsdk:"id"`
	Region           types.String `tfsdk:"region"`
	SecurityPolicies types.Set    `tfsdk:"security_policies"`
}

var _ basetypes.ObjectTypable = SecurityPoliciesType{}

type SecurityPoliciesType struct {
	basetypes.ObjectType
}

func (t SecurityPoliciesType) Equal(o attr.Type) bool {
	other, ok := o.(SecurityPoliciesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SecurityPoliciesType) String() string {
	return "SecurityPoliciesType"
}

func (t SecurityPoliciesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	settingsDescriptionAttribute, ok := attributes["settings_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`settings_description is missing from object`)

		return nil, diags
	}

	settingsDescriptionVal, ok := settingsDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`settings_description expected to be basetypes.StringValue, was: %T`, settingsDescriptionAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return nil, diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SecurityPoliciesValue{
		Description:         descriptionVal,
		Id:                  idVal,
		Name:                nameVal,
		SettingsDescription: settingsDescriptionVal,
		Version:             versionVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewSecurityPoliciesValueNull() SecurityPoliciesValue {
	return SecurityPoliciesValue{
		state: attr.ValueStateNull,
	}
}

func NewSecurityPoliciesValueUnknown() SecurityPoliciesValue {
	return SecurityPoliciesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSecurityPoliciesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SecurityPoliciesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SecurityPoliciesValue Attribute Value",
				"While creating a SecurityPoliciesValue value, a missing attribute value was detected. "+
					"A SecurityPoliciesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SecurityPoliciesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SecurityPoliciesValue Attribute Type",
				"While creating a SecurityPoliciesValue value, an invalid attribute value was detected. "+
					"A SecurityPoliciesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SecurityPoliciesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SecurityPoliciesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SecurityPoliciesValue Attribute Value",
				"While creating a SecurityPoliciesValue value, an extra attribute value was detected. "+
					"A SecurityPoliciesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SecurityPoliciesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSecurityPoliciesValueUnknown(), diags
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewSecurityPoliciesValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewSecurityPoliciesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewSecurityPoliciesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	settingsDescriptionAttribute, ok := attributes["settings_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`settings_description is missing from object`)

		return NewSecurityPoliciesValueUnknown(), diags
	}

	settingsDescriptionVal, ok := settingsDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`settings_description expected to be basetypes.StringValue, was: %T`, settingsDescriptionAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return NewSecurityPoliciesValueUnknown(), diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return NewSecurityPoliciesValueUnknown(), diags
	}

	return SecurityPoliciesValue{
		Description:         descriptionVal,
		Id:                  idVal,
		Name:                nameVal,
		SettingsDescription: settingsDescriptionVal,
		Version:             versionVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewSecurityPoliciesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SecurityPoliciesValue {
	object, diags := NewSecurityPoliciesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSecurityPoliciesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SecurityPoliciesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSecurityPoliciesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSecurityPoliciesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSecurityPoliciesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSecurityPoliciesValueMust(SecurityPoliciesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SecurityPoliciesType) ValueType(ctx context.Context) attr.Value {
	return SecurityPoliciesValue{}
}

var _ basetypes.ObjectValuable = SecurityPoliciesValue{}

type SecurityPoliciesValue struct {
	Description         basetypes.StringValue `tfsdk:"description"`
	Id                  basetypes.StringValue `tfsdk:"id"`
	Name                basetypes.StringValue `tfsdk:"name"`
	SettingsDescription basetypes.StringValue `tfsdk:"settings_description"`
	Version             basetypes.StringValue `tfsdk:"version"`
	state               attr.ValueState
}

func (v SecurityPoliciesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["settings_description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.SettingsDescription.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["settings_description"] = val

		val, err = v.Version.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SecurityPoliciesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SecurityPoliciesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SecurityPoliciesValue) String() string {
	return "SecurityPoliciesValue"
}

func (v SecurityPoliciesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"description":          basetypes.StringType{},
		"id":                   basetypes.StringType{},
		"name":                 basetypes.StringType{},
		"settings_description": basetypes.StringType{},
		"version":              basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"description":          v.Description,
			"id":                   v.Id,
			"name":                 v.Name,
			"settings_description": v.SettingsDescription,
			"version":              v.Version,
		})

	return objVal, diags
}

func (v SecurityPoliciesValue) Equal(o attr.Value) bool {
	other, ok := o.(SecurityPoliciesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.SettingsDescription.Equal(other.SettingsDescription) {
		return false
	}

	if !v.Version.Equal(other.Version) {
		return false
	}

	return true
}

func (v SecurityPoliciesValue) Type(ctx context.Context) attr.Type {
	return SecurityPoliciesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SecurityPoliciesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"description":          basetypes.StringType{},
		"id":                   basetypes.StringType{},
		"name":                 basetypes.StringType{},
		"settings_description": basetypes.StringType{},
		"version":              basetypes.StringType{},
	}
}
