// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_s3_account

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func S3AccountResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_key": schema.StringAttribute{
				Computed:            true,
				Description:         "Access key for the S3 account.",
				MarkdownDescription: "Access key for the S3 account.",
			},
			"account_id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the S3 account in Hotbox S3 service.",
				MarkdownDescription: "ID of the S3 account in Hotbox S3 service.",
			},
			"account_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the S3 account in Hotbox S3 service.",
				MarkdownDescription: "Name of the S3 account in Hotbox S3 service.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "S3 account creation timestamp.",
				MarkdownDescription: "S3 account creation timestamp.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description of the S3 account. Changing this creates a new resource.",
				MarkdownDescription: "Description of the S3 account. Changing this creates a new resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the S3 account.",
				MarkdownDescription: "ID of the S3 account.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the S3 account. The name must be unique. The length must be between 3 and 32 characters. Changing this creates a new resource.",
				MarkdownDescription: "Name of the S3 account. The name must be unique. The length must be between 3 and 32 characters. Changing this creates a new resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 32),
					stringvalidator.RegexMatches(regexp.MustCompile("^[0-9a-zA-Z_-]+$"), ""),
				},
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region in which to obtain the IAM Service Users client. If omitted, the `region` argument of the provider is used. Changing this creates a new resource.",
				MarkdownDescription: "The region in which to obtain the IAM Service Users client. If omitted, the `region` argument of the provider is used. Changing this creates a new resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"secret_key": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				Description:         "Secret key for the S3 account. _note_ This is a sensitive attribute.",
				MarkdownDescription: "Secret key for the S3 account. _note_ This is a sensitive attribute.",
			},
		},
		Description: "Manages an IAM S3 account within VKCS.",
	}
}

type S3AccountModel struct {
	AccessKey   types.String `tfsdk:"access_key"`
	AccountId   types.String `tfsdk:"account_id"`
	AccountName types.String `tfsdk:"account_name"`
	CreatedAt   types.String `tfsdk:"created_at"`
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Region      types.String `tfsdk:"region"`
	SecretKey   types.String `tfsdk:"secret_key"`
}
