provider:
  name: vkcs
resources:
  cluster:
    create:
      path: /api/clusters
      method: POST
    read:
      path: /api/clusters/{cluster_id}
      method: GET
    schema:
      ignores:
        - configs.features
        - configs.users
        - configs.warehouses.extensions
        - configs.warehouses.users
        - status
        - status_description
        - pod_groups.pod_group_template_id
        - pod_groups.node_processes
        - upgrades
        - floating_ip_pool
        - info
        - project_id
        - import_source
      attributes:
        aliases:
          cluster_id: id
        overrides:
          id:
            description: ID of the cluster.
          name:
            description: Name of the cluster.
          product_name:
            description: Name of the product.
          product_version:
            description: Version of the product.
          product_type:
            description: Type of the product.
          cluster_template_id:
            description: ID of the cluster template.
          network_id:
            description: ID of the cluster network.
          configs:
            description: Product configuration.
          configs.maintenance:
            description: Maintenance settings.
          configs.maintenance.start:
            description: Maintenance cron schedule.
          configs.maintenance.backup:
            description: Backup settings.
          configs.maintenance.backup.full:
            description: Full backup settings.
          configs.maintenance.backup.full.start:
            description: Full backup schedule.
          configs.maintenance.backup.full.keep_count:
            description: Full backup keep count.
          configs.maintenance.backup.full.keep_time:
            description: Full backup keep time.
          configs.maintenance.backup.full.enabled:
            description: Whether full backup is enabled.
          configs.maintenance.backup.incremental:
            description: Incremental backup settings.
          configs.maintenance.backup.incremental.start:
            description: Incremental backup schedule.
          configs.maintenance.backup.incremental.keep_count:
            description: Incremental backup keep count.
          configs.maintenance.backup.incremental.keep_time:
            description: Incremental backup keep time.
          configs.maintenance.backup.incremental.enabled:
            description: Whether incremental backup is enabled.
          configs.maintenance.backup.differential:
            description: Differential backup settings.
          configs.maintenance.backup.differential.start:
            description: Differential backup schedule.
          configs.maintenance.backup.differential.keep_count:
            description: Differential backup keep count.
          configs.maintenance.backup.differential.keep_time:
            description: Differential backup keep time.
          configs.maintenance.backup.differential.enabled:
            description: Whether differential backup is enabled.
          configs.maintenance.crontabs:
            description: Cron tabs settings.
          configs.maintenance.crontabs.name:
            description: Cron tab name.
          configs.maintenance.crontabs.start:
            description: Cron tab schedule.
          configs.maintenance.crontabs.settings:
            description: Additional cron settings.
          configs.maintenance.crontabs.settings.alias:
            description: Setting alias.
          configs.maintenance.crontabs.settings.value:
            description: Setting value.
          configs.maintenance.crontabs.required:
            description: Whether cron tab is required.
          configs.settings:
            description: Additional common settings.
          configs.settings.alias:
            description: Setting alias.
          configs.settings.value:
            description: Setting value.
          configs.warehouses:
            description: Warehouses settings.
          configs.warehouses.name:
            description: Warehouse name.
          configs.warehouses.connections:
            description: Warehouse connections.
          configs.warehouses.connections.plug:
            description: Connection plug.
          configs.warehouses.connections.name:
            description: Connection name.
          configs.warehouses.connections.settings:
            description: Additional warehouse settings.
          configs.warehouses.connections.settings.alias:
            description: Setting alias.
          configs.warehouses.connections.settings.value:
            description: Setting value.
          configs.warehouses.connections.id:
            description: Connection ID.
          configs.warehouses.connections.created_at:
            description: Connection creation timestamp.
          configs.warehouses.id:
            description: Warehouse ID.
          description:
            description: Cluster description.
          pod_groups:
            description: Cluster pod groups.
          pod_groups.count:
            description: Pod count.
          pod_groups.floating_ip_pool:
            description: Floating IP pool ID.
          pod_groups.resource:
            description: Resource request settings.
          pod_groups.resource.cpu_request:
            description: Resource request settings.
          pod_groups.resource.ram_request:
            description: RAM request settings.
          pod_groups.resource.cpu_limit:
            description: CPU limit.
          pod_groups.resource.ram_limit:
            description: RAM limit settings.
          pod_groups.volumes:
            description: Volumes settings.
          pod_groups.volumes.type:
            description: Volume type.
          pod_groups.volumes.count:
            description: Volume count.
          pod_groups.volumes.storageClassName:
            description: Storage class name.
          pod_groups.volumes.storage:
            description: Storage size.
          pod_groups.id:
            description: Pod group ID.
          pod_groups.alias:
            description: Pod group alias.
          pod_groups.name:
            description: Pod group name.
          subnet_id:
            description: ID of the cluster subnet.
          stack_id:
            description: ID of the cluster stack.
          availability_zone:
            description: Availability zone to create cluster in.
          multiaz:
            description: Enables multi az support.
          created_at:
            description: Cluster creation timestamp.
