provider:
  name: vkcs
resources:
  cluster:
    create:
      path: /api/clusters
      method: POST
    read:
      path: /api/clusters/{cluster_id}
      method: GET
    schema:
      ignores:
        - configs.features
        - configs.users.access
        - configs.users.connection_store
        - configs.users.settings
        - configs.warehouses.connections.connection_store
        - configs.warehouses.connections.connection_store_id
        - configs.warehouses.extensions
        - configs.warehouses.users
        - status
        - status_description
        - pod_groups.pod_group_template_id
        - pod_groups.node_processes
        - pod_groups.replicas
        - upgrades
        - project_id
        - import_source
        - blocking_operation_id
        - operator_status
      attributes:
        aliases:
          cluster_id: id
        overrides:
          id:
            description: ID of the cluster.
          name:
            description: Name of the cluster.
          product_name:
            description: Name of the product.
          product_version:
            description: Version of the product. Changing this creates a new resource.
          product_type:
            description: Type of the product.
          cluster_template_id:
            description: ID of the cluster template. Changing this creates a new resource.
          network_id:
            description: ID of the cluster network. Changing this creates a new resource.
          configs:
            description: Product configuration.
          configs.maintenance:
            description: Maintenance settings. Changing this creates a new resource.
          configs.maintenance.start:
            description: Maintenance cron schedule. Defined in UTC. Changing this creates a new resource.
          configs.maintenance.backup:
            description: Backup settings. Changing this creates a new resource.
          configs.maintenance.backup.full:
            description: Full backup settings. Changing this creates a new resource.
          configs.maintenance.backup.full.start:
            description: Full backup schedule. Defined in UTC. Changing this creates a new resource.
          configs.maintenance.backup.full.keep_count:
            description: Full backup keep count. Changing this creates a new resource.
          configs.maintenance.backup.full.keep_time:
            description: Full backup keep time. Changing this creates a new resource.
          configs.maintenance.backup.full.enabled:
            description: Whether full backup is enabled.
          configs.maintenance.backup.incremental:
            description: Incremental backup settings. Changing this creates a new resource.
          configs.maintenance.backup.incremental.start:
            description: Incremental backup schedule. Defined in UTC. Changing this creates a new resource.
          configs.maintenance.backup.incremental.keep_count:
            description: Incremental backup keep count. Changing this creates a new resource.
          configs.maintenance.backup.incremental.keep_time:
            description: Incremental backup keep time. Changing this creates a new resource.
          configs.maintenance.backup.incremental.enabled:
            description: Whether incremental backup is enabled.
          configs.maintenance.backup.differential:
            description: Differential backup settings. Changing this creates a new resource.
          configs.maintenance.backup.differential.start:
            description: Differential backup schedule. Defined in UTC. Changing this creates a new resource.
          configs.maintenance.backup.differential.keep_count:
            description: Differential backup keep count. Changing this creates a new resource.
          configs.maintenance.backup.differential.keep_time:
            description: Differential backup keep time. Changing this creates a new resource.
          configs.maintenance.backup.differential.enabled:
            description: Whether differential backup is enabled.
          configs.maintenance.crontabs:
            description: Cron tabs settings. Changing this creates a new resource.
          configs.maintenance.crontabs.name:
            description: Cron tab name. Changing this creates a new resource.
          configs.maintenance.crontabs.start:
            description: Cron tab schedule. Defined in UTC. Changing this creates a new resource.
          configs.maintenance.crontabs.settings:
            description: Additional cron settings. Changing this creates a new resource.
          configs.maintenance.crontabs.settings.alias:
            description: Setting alias. Changing this creates a new resource.
          configs.maintenance.crontabs.settings.value:
            description: Setting value. Changing this creates a new resource.
          configs.maintenance.crontabs.required:
            description: Whether cron tab is required.
          configs.settings:
            description: Additional common settings.
          configs.settings.alias:
            description: Setting alias.
          configs.settings.value:
            description: Setting value.
          configs.users:
            description: Users settings.
          configs.users.username:
            description: Username
          configs.users.password:
            description: Password. Changing this creates a new resource.
          configs.users.role:
            description: User role. Changing this creates a new resource.
          configs.warehouses:
            description: Warehouses settings. Changing this creates a new resource.
          configs.warehouses.name:
            description: Warehouse name. Changing this creates a new resource.
          configs.warehouses.connections:
            description: Warehouse connections. Changing this creates a new resource.
          configs.warehouses.connections.plug:
            description: Connection plug. Changing this creates a new resource.
          configs.warehouses.connections.name:
            description: Connection name. Changing this creates a new resource.
          configs.warehouses.connections.settings:
            description: Additional warehouse settings. Changing this creates a new resource.
          configs.warehouses.connections.settings.alias:
            description: Setting alias. Changing this creates a new resource.
          configs.warehouses.connections.settings.value:
            description: Setting value. Changing this creates a new resource.
          configs.warehouses.connections.id:
            description: Connection ID.
          configs.warehouses.connections.created_at:
            description: Connection creation timestamp.
          configs.warehouses.id:
            description: Warehouse ID.
          description:
            description: Cluster description.
          floating_ip_pool:
            description: Floating IP pool ID. Use `auto` for autoselect. Changing this creates a new resource.
          info:
            description: Application info
          info.services:
            description: Application services info
          info.services.connection_string:
            description: Service connection string
          info.services.description:
            description: Service description
          info.services.exposed:
            description: Whether service is exposed
          info.services.type:
            description: Service type
          pod_groups:
            description: Cluster pod groups. Changing this creates a new resource.
          pod_groups.count:
            description: Pod count. Changing this creates a new resource.
          pod_groups.floating_ip_pool:
            description: Floating IP pool ID. Changing this creates a new resource.
          pod_groups.resource:
            description: Resource request settings. Changing this creates a new resource.
          pod_groups.resource.cpu_request:
            description: Resource request settings. Changing this creates a new resource.
          pod_groups.resource.ram_request:
            description: RAM request settings. Changing this creates a new resource.
          pod_groups.resource.cpu_limit:
            description: CPU limit.
          pod_groups.resource.ram_limit:
            description: RAM limit settings.
          pod_groups.volumes:
            description: Volumes settings. Changing this creates a new resource.
          pod_groups.volumes.type:
            description: Volume type. Changing this creates a new resource.
          pod_groups.volumes.count:
            description: Volume count. Changing this creates a new resource.
          pod_groups.volumes.storageClassName:
            description: Storage class name. Changing this creates a new resource.
          pod_groups.volumes.storage:
            description: Storage size. Changing this creates a new resource.
          pod_groups.id:
            description: Pod group ID.
          pod_groups.alias:
            description: Pod group alias.
          pod_groups.name:
            description: Pod group name.
          subnet_id:
            description: ID of the cluster subnet. Changing this creates a new resource.
          stack_id:
            description: ID of the cluster stack. Changing this creates a new resource.
          availability_zone:
            description: Availability zone to create cluster in. Changing this creates a new resource.
          multiaz:
            description: Enables multi az support. Changing this creates a new resource.
          created_at:
            description: Cluster creation timestamp.
data_sources:
  products:
    read:
      path: /api/products
      method: GET
    schema:
      ignores:
        - features
        - mode
        - products.configs
        - sockets
      attributes:
        overrides:
          products:
            description: List of products information
          products.product_name:
            description: Product name
          products.product_version:
            description: Product version
  template:
    read:
      path: /api/templates
      method: GET
    schema:
      ignores:
        - cluster_templates.pod_groups.meta
        - cluster_templates.configs
        - cluster_templates.meta
        - cluster_templates.presets
        - cluster_templates.created_at
        - cluster_templates.description
        - cluster_templates.product_type
        - cluster_templates.template_type
        - cluster_templates.multiaz
        - cluster_templates.availability_zone
        - cluster_templates.is_hidden
        - cluster_templates.pod_groups.created_at
        - cluster_templates.pod_groups.node_processes
        - cluster_templates.pod_groups.template_type
        - cluster_templates.pod_groups.backref
        - cluster_templates.pod_groups.alias
        - cluster_templates.pod_groups.cluster_template_id
        - cluster_templates.pod_groups.id
        - cluster_templates.pod_groups.description
      attributes:
        overrides:
          cluster_templates:
            description: List of cluster templates.
          cluster_templates.id:
            description: ID of the cluster template.
          cluster_templates.name:
            description: Name of the cluster template.
          cluster_templates.product_name:
            description: Product name.
          cluster_templates.product_version:
            description: Product version.
          cluster_templates.pod_groups:
            description: List of pod groups in the template.
          cluster_templates.pod_groups.name:
            description: Pod group name.
          cluster_templates.pod_groups.resource:
            description: Resource settings for the pod group.
          cluster_templates.pod_groups.resource.cpu_request:
            description: CPU request for the pod group.
          cluster_templates.pod_groups.resource.cpu_margin:
            description: CPU margin for the pod group.
          cluster_templates.pod_groups.resource.ram_request:
            description: RAM request for the pod group.
          cluster_templates.pod_groups.resource.ram_margin:
            description: RAM margin for the pod group.
          cluster_templates.pod_groups.volumes:
            description: Volumes configuration for the pod group.
          cluster_templates.pod_groups.volumes.count:
            description: Volume count.
          cluster_templates.pod_groups.volumes.storageClassName:
            description: Storage class name for the volume.
          cluster_templates.pod_groups.volumes.storage:
            description: Volume storage size.
          cluster_templates.pod_groups.count:
            description: Number of pods in the pod group.
