provider:
  name: vkcs
resources:
  cluster:
    create:
      path: /api/clusters
      method: POST
    read:
      path: /api/clusters/{cluster_id}
      method: GET
    schema:
      ignores:
        - configs.features
        - configs.users
        - configs.warehouses.extensions
        - configs.warehouses.users
        - status
        - status_description
        - pod_groups.pod_group_template_id
        - pod_groups.node_processes
        - upgrades
        - floating_ip_pool
        - info
        - project_id
        - import_source
      attributes:
        aliases:
          cluster_id: id
        overrides:
          id:
            description: ID of the cluster.
          name:
            description: Name of the cluster.
          product_name:
            description: Name of the product.
          product_version:
            description: Version of the product. Changing this creates a new resource.
          product_type:
            description: Type of the product.
          cluster_template_id:
            description: ID of the cluster template. Changing this creates a new resource.
          network_id:
            description: ID of the cluster network. Changing this creates a new resource.
          configs:
            description: Product configuration.
          configs.maintenance:
            description: Maintenance settings. Changing this creates a new resource.
          configs.maintenance.start:
            description: Maintenance cron schedule. Changing this creates a new resource.
          configs.maintenance.backup:
            description: Backup settings. Changing this creates a new resource.
          configs.maintenance.backup.full:
            description: Full backup settings. Changing this creates a new resource.
          configs.maintenance.backup.full.start:
            description: Full backup schedule. Changing this creates a new resource.
          configs.maintenance.backup.full.keep_count:
            description: Full backup keep count. Changing this creates a new resource.
          configs.maintenance.backup.full.keep_time:
            description: Full backup keep time. Changing this creates a new resource.
          configs.maintenance.backup.full.enabled:
            description: Whether full backup is enabled.
          configs.maintenance.backup.incremental:
            description: Incremental backup settings. Changing this creates a new resource.
          configs.maintenance.backup.incremental.start:
            description: Incremental backup schedule. Changing this creates a new resource.
          configs.maintenance.backup.incremental.keep_count:
            description: Incremental backup keep count. Changing this creates a new resource.
          configs.maintenance.backup.incremental.keep_time:
            description: Incremental backup keep time. Changing this creates a new resource.
          configs.maintenance.backup.incremental.enabled:
            description: Whether incremental backup is enabled.
          configs.maintenance.backup.differential:
            description: Differential backup settings. Changing this creates a new resource.
          configs.maintenance.backup.differential.start:
            description: Differential backup schedule. Changing this creates a new resource.
          configs.maintenance.backup.differential.keep_count:
            description: Differential backup keep count. Changing this creates a new resource.
          configs.maintenance.backup.differential.keep_time:
            description: Differential backup keep time. Changing this creates a new resource.
          configs.maintenance.backup.differential.enabled:
            description: Whether differential backup is enabled.
          configs.maintenance.crontabs:
            description: Cron tabs settings. Changing this creates a new resource.
          configs.maintenance.crontabs.name:
            description: Cron tab name. Changing this creates a new resource.
          configs.maintenance.crontabs.start:
            description: Cron tab schedule. Changing this creates a new resource.
          configs.maintenance.crontabs.settings:
            description: Additional cron settings. Changing this creates a new resource.
          configs.maintenance.crontabs.settings.alias:
            description: Setting alias. Changing this creates a new resource.
          configs.maintenance.crontabs.settings.value:
            description: Setting value. Changing this creates a new resource.
          configs.maintenance.crontabs.required:
            description: Whether cron tab is required.
          configs.settings:
            description: Additional common settings.
          configs.settings.alias:
            description: Setting alias.
          configs.settings.value:
            description: Setting value.
          configs.warehouses:
            description: Warehouses settings. Changing this creates a new resource.
          configs.warehouses.name:
            description: Warehouse name. Changing this creates a new resource.
          configs.warehouses.connections:
            description: Warehouse connections. Changing this creates a new resource.
          configs.warehouses.connections.plug:
            description: Connection plug. Changing this creates a new resource.
          configs.warehouses.connections.name:
            description: Connection name. Changing this creates a new resource.
          configs.warehouses.connections.settings:
            description: Additional warehouse settings. Changing this creates a new resource.
          configs.warehouses.connections.settings.alias:
            description: Setting alias. Changing this creates a new resource.
          configs.warehouses.connections.settings.value:
            description: Setting value. Changing this creates a new resource.
          configs.warehouses.connections.id:
            description: Connection ID.
          configs.warehouses.connections.created_at:
            description: Connection creation timestamp.
          configs.warehouses.id:
            description: Warehouse ID.
          description:
            description: Cluster description.
          pod_groups:
            description: Cluster pod groups. Changing this creates a new resource.
          pod_groups.count:
            description: Pod count. Changing this creates a new resource.
          pod_groups.floating_ip_pool:
            description: Floating IP pool ID. Changing this creates a new resource.
          pod_groups.resource:
            description: Resource request settings. Changing this creates a new resource.
          pod_groups.resource.cpu_request:
            description: Resource request settings. Changing this creates a new resource.
          pod_groups.resource.ram_request:
            description: RAM request settings. Changing this creates a new resource.
          pod_groups.resource.cpu_limit:
            description: CPU limit.
          pod_groups.resource.ram_limit:
            description: RAM limit settings.
          pod_groups.volumes:
            description: Volumes settings. Changing this creates a new resource.
          pod_groups.volumes.type:
            description: Volume type. Changing this creates a new resource.
          pod_groups.volumes.count:
            description: Volume count. Changing this creates a new resource.
          pod_groups.volumes.storageClassName:
            description: Storage class name. Changing this creates a new resource.
          pod_groups.volumes.storage:
            description: Storage size. Changing this creates a new resource.
          pod_groups.id:
            description: Pod group ID.
          pod_groups.alias:
            description: Pod group alias.
          pod_groups.name:
            description: Pod group name.
          subnet_id:
            description: ID of the cluster subnet. Changing this creates a new resource.
          stack_id:
            description: ID of the cluster stack. Changing this creates a new resource.
          availability_zone:
            description: Availability zone to create cluster in. Changing this creates a new resource.
          multiaz:
            description: Enables multi az support. Changing this creates a new resource.
          created_at:
            description: Cluster creation timestamp.
data_sources:
  products:
    read:
      path: /api/products
      method: GET
    schema:
      ignores:
        - features
        - mode
        - products.configs
      attributes:
        overrides:
          products:
            description: List of products information
          products.product_name:
            description: Product name
          products.product_version:
            description: Product version
