#!/usr/bin/env bash
set -euo pipefail

list_dirs() {
    local roots=("$@")
    if (( ${#roots[@]} == 0 )); then
        roots=(examples)
    fi
    find "${roots[@]}" -name '*.tf' -not -path '*/.terraform/*' -print0 \
        | xargs -0 -n1 dirname | sort -u
}

dir_needs_random() {
    local dir="$1"
    local exclude="$2"
    local pattern='\brandom_(password|string|id|integer|uuid|bytes|shuffle|pet)\b'
    find "${dir}" -maxdepth 1 -name '*.tf' -not -name "${exclude}" -print0 \
        | xargs -0 grep -qE "${pattern}" 2>/dev/null
}

dir_has_required_providers() {
    local dir="$1"
    local exclude="$2"
    find "${dir}" -maxdepth 1 -name '*.tf' -not -name "${exclude}" -print0 \
        | xargs -0 grep -l "required_providers" >/dev/null 2>&1
}

write_versions_file() {
    local dir="$1"
    local filename="$2"
    local needs_random="$3"
    local target="${dir}/${filename}"
    {
        echo "# Generated by scripts/prepare-examples-ide.sh — DO NOT COMMIT."
        echo "# Gitignored. Lets terraform-ls resolve provider schemas."
        echo "terraform {"
        echo "  required_providers {"
        echo "    vkcs = {"
        echo "      source = \"vk-cs/vkcs\""
        echo "    }"
        if [[ "${needs_random}" == "yes" ]]; then
            echo "    random = {"
            echo "      source = \"hashicorp/random\""
            echo "    }"
        fi
        echo "  }"
        echo "}"
    } > "${target}"
}

clean_files() {
    local filename="$1"
    local -a files
    mapfile -t files < <(find examples -name "${filename}" -not -path '*/.terraform/*')
    local f
    for f in "${files[@]}"; do
        rm -f "${f}"
    done
    echo "removed ${#files[@]} files"
}

main() {
    local repo_root
    repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
    cd "${repo_root}"

    local filename="_ide_versions.tf"

    if [[ "${1:-}" == "--clean" ]]; then
        clean_files "${filename}"
        return 0
    fi

    local -a dirs
    mapfile -t dirs < <(list_dirs "$@")

    local wrote=0
    local skipped=0
    local dir needs_random
    for dir in "${dirs[@]}"; do
        if dir_has_required_providers "${dir}" "${filename}"; then
            echo "  skip  ${dir} (already has required_providers)"
            skipped=$((skipped + 1))
            continue
        fi
        if dir_needs_random "${dir}" "${filename}"; then
            needs_random="yes"
        else
            needs_random="no"
        fi
        write_versions_file "${dir}" "${filename}" "${needs_random}"
        if [[ "${needs_random}" == "yes" ]]; then
            echo "  wrote ${dir}/${filename} (vkcs + random)"
        else
            echo "  wrote ${dir}/${filename} (vkcs)"
        fi
        wrote=$((wrote + 1))
    done

    echo
    echo "==> ${wrote} written, ${skipped} skipped"
}

main "$@"
