// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_kubernetes_node_group_v2

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/vk-cs/terraform-provider-vkcs/vkcs/kubernetes/plan_modifiers"
	"github.com/vk-cs/terraform-provider-vkcs/vkcs/kubernetes/schema_validators"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func KubernetesNodeGroupV2ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"auto_scale_max_size": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The maximum number of nodes the autoscaler may scale out to. Must be greater than or equal to 0 and also greater than or equal to `auto_scale_min_size`. Required if scale_type is `auto_scale`.",
				MarkdownDescription: "The maximum number of nodes the autoscaler may scale out to. Must be greater than or equal to 0 and also greater than or equal to `auto_scale_min_size`. Required if scale_type is `auto_scale`.",
				PlanModifiers: []planmodifier.Int64{
					plan_modifiers.NullIfFixedScaleType(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"auto_scale_min_size": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The minimum number of nodes the autoscaler may scale down to. Must be greater than or equal to 0. Required if `scale_type` is `auto_scale`.",
				MarkdownDescription: "The minimum number of nodes the autoscaler may scale down to. Must be greater than or equal to 0. Required if `scale_type` is `auto_scale`.",
				PlanModifiers: []planmodifier.Int64{
					plan_modifiers.NullIfFixedScaleType(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"auto_scale_node_count": schema.Int64Attribute{
				Computed:            true,
				Description:         "During the cluster lifecycle, it indicates the current number of nodes in the node group if `scale_type` is `auto_scale`.",
				MarkdownDescription: "During the cluster lifecycle, it indicates the current number of nodes in the node group if `scale_type` is `auto_scale`.",
				PlanModifiers: []planmodifier.Int64{
					plan_modifiers.NullIfFixedScaleType(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"availability_zone": schema.StringAttribute{
				Required:            true,
				Description:         "The availability zone where the nodes will be placed. **Forces replacement** on change.",
				MarkdownDescription: "The availability zone where the nodes will be placed. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"cluster_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the parent cluster. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the parent cluster. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.KSUIDValidator{},
				},
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The timestamp when the node group was created (ISO 8601 format).",
				MarkdownDescription: "The timestamp when the node group was created (ISO 8601 format).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"disk_size": schema.Int64Attribute{
				Required:            true,
				Description:         "The size of the root volume in GB. Minimum is 1 GB. **Forces replacement** on change.",
				MarkdownDescription: "The size of the root volume in GB. Minimum is 1 GB. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"disk_type": schema.StringAttribute{
				Required:            true,
				Description:         "The type of root volume (e.g., `ceph-ssd`). Use `vkcs_kubernetes_volume_types_v2` to list available types. **Forces replacement** on change.",
				MarkdownDescription: "The type of root volume (e.g., `ceph-ssd`). Use `vkcs_kubernetes_volume_types_v2` to list available types. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"fixed_scale_node_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The desired number of nodes. Minimum value is 0. Required if `scale_type` is `fixed_scale`.",
				MarkdownDescription: "The desired number of nodes. Minimum value is 0. Required if `scale_type` is `fixed_scale`.",
				PlanModifiers: []planmodifier.Int64{
					plan_modifiers.NullIfAutoScaleType(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the node group.",
				MarkdownDescription: "The unique identifier of the node group.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"labels": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Kubernetes labels to apply to nodes in this group. Keys/values must be valid Kubernetes label strings.",
				MarkdownDescription: "Kubernetes labels to apply to nodes in this group. Keys/values must be valid Kubernetes label strings.",
				Validators: []validator.Map{
					schema_validators.KubernetesNodeLabelsValidator{},
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A unique name for the node group within the cluster. Must be 3-25 characters, lowercase alphanumeric and hyphens only. **Forces replacement** on change.",
				MarkdownDescription: "A unique name for the node group within the cluster. Must be 3-25 characters, lowercase alphanumeric and hyphens only. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.NodeGroupNameValidator{},
				},
			},
			"node_flavor": schema.StringAttribute{
				Required:            true,
				Description:         "The flavor ID for each node. Changing this triggers a rolling upgrade of the nodes.",
				MarkdownDescription: "The flavor ID for each node. Changing this triggers a rolling upgrade of the nodes.",
				Validators: []validator.String{
					schema_validators.UUIDValidator{},
				},
			},
			"parallel_upgrade_chunk": schema.Int64Attribute{
				Required:            true,
				Description:         "The maximum percentage of nodes (1-100) that can be upgraded simultaneously during a rolling upgrade.",
				MarkdownDescription: "The maximum percentage of nodes (1-100) that can be upgraded simultaneously during a rolling upgrade.",
				Validators: []validator.Int64{
					int64validator.Between(1, 100),
				},
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region where the node group will be created. Defaults to provider's `region`. **Forces replacement** on change.",
				MarkdownDescription: "The region where the node group will be created. Defaults to provider's `region`. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"scale_type": schema.StringAttribute{
				Required:            true,
				Description:         "Type of scaling for the node group. Must be either `fixed_scale` or `auto_scale`. If `scale_type` is `auto_scale`, the condition `auto_scale_min_size` <= `auto_scale_max_size` must be met.",
				MarkdownDescription: "Type of scaling for the node group. Must be either `fixed_scale` or `auto_scale`. If `scale_type` is `auto_scale`, the condition `auto_scale_min_size` <= `auto_scale_max_size` must be met.",
				Validators: []validator.String{
					stringvalidator.OneOf("fixed_scale", "auto_scale"),
				},
			},
			"taints": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"effect": schema.StringAttribute{
							Required:            true,
							Description:         "The effect of the taint. Must be one of: `NoSchedule`, `PreferNoSchedule`, `NoExecute`.",
							MarkdownDescription: "The effect of the taint. Must be one of: `NoSchedule`, `PreferNoSchedule`, `NoExecute`.",
						},
						"key": schema.StringAttribute{
							Required:            true,
							Description:         "The taint key. Must be a valid Kubernetes label key.",
							MarkdownDescription: "The taint key. Must be a valid Kubernetes label key.",
						},
						"value": schema.StringAttribute{
							Required:            true,
							Description:         "The taint value. Must be a valid Kubernetes label value.",
							MarkdownDescription: "The taint value. Must be a valid Kubernetes label value.",
						},
					},
					CustomType: TaintsType{
						ObjectType: types.ObjectType{
							AttrTypes: TaintsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Description:         "Taints to apply to nodes. Each taint must have `key`, `value`, and `effect` (one of `NoSchedule`, `PreferNoSchedule`, `NoExecute`).",
				MarkdownDescription: "Taints to apply to nodes. Each taint must have `key`, `value`, and `effect` (one of `NoSchedule`, `PreferNoSchedule`, `NoExecute`).",
				Validators: []validator.Set{
					schema_validators.KubernetesNodeTaintsValidator{},
				},
			},
			"timeouts": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"create": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Timeout for create operation (e.g., `60m`, `2h`). Default is `30m`.",
						MarkdownDescription: "Timeout for create operation (e.g., `60m`, `2h`). Default is `30m`.",
						Validators: []validator.String{
							schema_validators.TimeoutValidator{},
						},
					},
					"delete": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Timeout for delete operation (e.g., `30m`, `1h`). Default is `30m`.",
						MarkdownDescription: "Timeout for delete operation (e.g., `30m`, `1h`). Default is `30m`.",
						Validators: []validator.String{
							schema_validators.TimeoutValidator{},
						},
					},
					"update": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Timeout for update operation (e.g., `120m`, `3h`). Default is `30m`.",
						MarkdownDescription: "Timeout for update operation (e.g., `120m`, `3h`). Default is `30m`.",
						Validators: []validator.String{
							schema_validators.TimeoutValidator{},
						},
					},
				},
				CustomType: TimeoutsType{
					ObjectType: types.ObjectType{
						AttrTypes: TimeoutsValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Timeouts configuration for create, update and delete operations.",
				MarkdownDescription: "Timeouts configuration for create, update and delete operations.",
			},
			"uuid": schema.StringAttribute{
				Computed:            true,
				Description:         "The node group's UUID. It is generated automatically.",
				MarkdownDescription: "The node group's UUID. It is generated automatically.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

type KubernetesNodeGroupV2Model struct {
	AutoScaleMaxSize     types.Int64   `tfsdk:"auto_scale_max_size"`
	AutoScaleMinSize     types.Int64   `tfsdk:"auto_scale_min_size"`
	AutoScaleNodeCount   types.Int64   `tfsdk:"auto_scale_node_count"`
	AvailabilityZone     types.String  `tfsdk:"availability_zone"`
	ClusterId            types.String  `tfsdk:"cluster_id"`
	CreatedAt            types.String  `tfsdk:"created_at"`
	DiskSize             types.Int64   `tfsdk:"disk_size"`
	DiskType             types.String  `tfsdk:"disk_type"`
	FixedScaleNodeCount  types.Int64   `tfsdk:"fixed_scale_node_count"`
	Id                   types.String  `tfsdk:"id"`
	Labels               types.Map     `tfsdk:"labels"`
	Name                 types.String  `tfsdk:"name"`
	NodeFlavor           types.String  `tfsdk:"node_flavor"`
	ParallelUpgradeChunk types.Int64   `tfsdk:"parallel_upgrade_chunk"`
	Region               types.String  `tfsdk:"region"`
	ScaleType            types.String  `tfsdk:"scale_type"`
	Taints               types.Set     `tfsdk:"taints"`
	Timeouts             TimeoutsValue `tfsdk:"timeouts"`
	Uuid                 types.String  `tfsdk:"uuid"`
}

var _ basetypes.ObjectTypable = TaintsType{}

type TaintsType struct {
	basetypes.ObjectType
}

func (t TaintsType) Equal(o attr.Type) bool {
	other, ok := o.(TaintsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TaintsType) String() string {
	return "TaintsType"
}

func (t TaintsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	effectAttribute, ok := attributes["effect"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`effect is missing from object`)

		return nil, diags
	}

	effectVal, ok := effectAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`effect expected to be basetypes.StringValue, was: %T`, effectAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TaintsValue{
		Effect: effectVal,
		Key:    keyVal,
		Value:  valueVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTaintsValueNull() TaintsValue {
	return TaintsValue{
		state: attr.ValueStateNull,
	}
}

func NewTaintsValueUnknown() TaintsValue {
	return TaintsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTaintsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TaintsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TaintsValue Attribute Value",
				"While creating a TaintsValue value, a missing attribute value was detected. "+
					"A TaintsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TaintsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TaintsValue Attribute Type",
				"While creating a TaintsValue value, an invalid attribute value was detected. "+
					"A TaintsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TaintsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TaintsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TaintsValue Attribute Value",
				"While creating a TaintsValue value, an extra attribute value was detected. "+
					"A TaintsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TaintsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTaintsValueUnknown(), diags
	}

	effectAttribute, ok := attributes["effect"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`effect is missing from object`)

		return NewTaintsValueUnknown(), diags
	}

	effectVal, ok := effectAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`effect expected to be basetypes.StringValue, was: %T`, effectAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewTaintsValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewTaintsValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewTaintsValueUnknown(), diags
	}

	return TaintsValue{
		Effect: effectVal,
		Key:    keyVal,
		Value:  valueVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTaintsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TaintsValue {
	object, diags := NewTaintsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTaintsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TaintsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTaintsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTaintsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTaintsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTaintsValueMust(TaintsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TaintsType) ValueType(ctx context.Context) attr.Value {
	return TaintsValue{}
}

var _ basetypes.ObjectValuable = TaintsValue{}

type TaintsValue struct {
	Effect basetypes.StringValue `tfsdk:"effect"`
	Key    basetypes.StringValue `tfsdk:"key"`
	Value  basetypes.StringValue `tfsdk:"value"`
	state  attr.ValueState
}

func (v TaintsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["effect"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Effect.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["effect"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TaintsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TaintsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TaintsValue) String() string {
	return "TaintsValue"
}

func (v TaintsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"effect": basetypes.StringType{},
		"key":    basetypes.StringType{},
		"value":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"effect": v.Effect,
			"key":    v.Key,
			"value":  v.Value,
		})

	return objVal, diags
}

func (v TaintsValue) Equal(o attr.Value) bool {
	other, ok := o.(TaintsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Effect.Equal(other.Effect) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v TaintsValue) Type(ctx context.Context) attr.Type {
	return TaintsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TaintsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"effect": basetypes.StringType{},
		"key":    basetypes.StringType{},
		"value":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TimeoutsType{}

type TimeoutsType struct {
	basetypes.ObjectType
}

func (t TimeoutsType) Equal(o attr.Type) bool {
	other, ok := o.(TimeoutsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TimeoutsType) String() string {
	return "TimeoutsType"
}

func (t TimeoutsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createAttribute, ok := attributes["create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`create is missing from object`)

		return nil, diags
	}

	createVal, ok := createAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`create expected to be basetypes.StringValue, was: %T`, createAttribute))
	}

	deleteAttribute, ok := attributes["delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delete is missing from object`)

		return nil, diags
	}

	deleteVal, ok := deleteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delete expected to be basetypes.StringValue, was: %T`, deleteAttribute))
	}

	updateAttribute, ok := attributes["update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`update is missing from object`)

		return nil, diags
	}

	updateVal, ok := updateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`update expected to be basetypes.StringValue, was: %T`, updateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TimeoutsValue{
		Create: createVal,
		Delete: deleteVal,
		Update: updateVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTimeoutsValueNull() TimeoutsValue {
	return TimeoutsValue{
		state: attr.ValueStateNull,
	}
}

func NewTimeoutsValueUnknown() TimeoutsValue {
	return TimeoutsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTimeoutsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TimeoutsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TimeoutsValue Attribute Value",
				"While creating a TimeoutsValue value, a missing attribute value was detected. "+
					"A TimeoutsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TimeoutsValue Attribute Type",
				"While creating a TimeoutsValue value, an invalid attribute value was detected. "+
					"A TimeoutsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TimeoutsValue Attribute Value",
				"While creating a TimeoutsValue value, an extra attribute value was detected. "+
					"A TimeoutsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TimeoutsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTimeoutsValueUnknown(), diags
	}

	createAttribute, ok := attributes["create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`create is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	createVal, ok := createAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`create expected to be basetypes.StringValue, was: %T`, createAttribute))
	}

	deleteAttribute, ok := attributes["delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delete is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	deleteVal, ok := deleteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delete expected to be basetypes.StringValue, was: %T`, deleteAttribute))
	}

	updateAttribute, ok := attributes["update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`update is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	updateVal, ok := updateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`update expected to be basetypes.StringValue, was: %T`, updateAttribute))
	}

	if diags.HasError() {
		return NewTimeoutsValueUnknown(), diags
	}

	return TimeoutsValue{
		Create: createVal,
		Delete: deleteVal,
		Update: updateVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTimeoutsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TimeoutsValue {
	object, diags := NewTimeoutsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTimeoutsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TimeoutsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTimeoutsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTimeoutsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTimeoutsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTimeoutsValueMust(TimeoutsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TimeoutsType) ValueType(ctx context.Context) attr.Value {
	return TimeoutsValue{}
}

var _ basetypes.ObjectValuable = TimeoutsValue{}

type TimeoutsValue struct {
	Create basetypes.StringValue `tfsdk:"create"`
	Delete basetypes.StringValue `tfsdk:"delete"`
	Update basetypes.StringValue `tfsdk:"update"`
	state  attr.ValueState
}

func (v TimeoutsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["create"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["delete"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["update"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Create.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["create"] = val

		val, err = v.Delete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["delete"] = val

		val, err = v.Update.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["update"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TimeoutsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TimeoutsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TimeoutsValue) String() string {
	return "TimeoutsValue"
}

func (v TimeoutsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"create": basetypes.StringType{},
		"delete": basetypes.StringType{},
		"update": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"create": v.Create,
			"delete": v.Delete,
			"update": v.Update,
		})

	return objVal, diags
}

func (v TimeoutsValue) Equal(o attr.Value) bool {
	other, ok := o.(TimeoutsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Create.Equal(other.Create) {
		return false
	}

	if !v.Delete.Equal(other.Delete) {
		return false
	}

	if !v.Update.Equal(other.Update) {
		return false
	}

	return true
}

func (v TimeoutsValue) Type(ctx context.Context) attr.Type {
	return TimeoutsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TimeoutsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"create": basetypes.StringType{},
		"delete": basetypes.StringType{},
		"update": basetypes.StringType{},
	}
}
