// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_s3_account

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func S3AccountDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_key": schema.StringAttribute{
				Computed:            true,
				Description:         "Access key for the S3 account.",
				MarkdownDescription: "Access key for the S3 account.",
			},
			"account_id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the S3 account in Hotbox S3 service.",
				MarkdownDescription: "ID of the S3 account in Hotbox S3 service.",
			},
			"account_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the S3 account in Hotbox S3 service.",
				MarkdownDescription: "Name of the S3 account in Hotbox S3 service.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "S3 account creation timestamp.",
				MarkdownDescription: "S3 account creation timestamp.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Description of the S3 account.",
				MarkdownDescription: "Description of the S3 account.",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of the S3 account. Conflicts with `name`.",
				MarkdownDescription: "ID of the S3 account. Conflicts with `name`.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Name of the S3 account. Conflicts with `id`.",
				MarkdownDescription: "Name of the S3 account. Conflicts with `id`.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region in which to obtain the IAM Service Users client. If omitted, the `region` argument of the provider is used.",
				MarkdownDescription: "The region in which to obtain the IAM Service Users client. If omitted, the `region` argument of the provider is used.",
			},
		},
		Description: "Use this data source to get information about an IAM S3 account.",
	}
}

type S3AccountModel struct {
	AccessKey   types.String `tfsdk:"access_key"`
	AccountId   types.String `tfsdk:"account_id"`
	AccountName types.String `tfsdk:"account_name"`
	CreatedAt   types.String `tfsdk:"created_at"`
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Region      types.String `tfsdk:"region"`
}
