// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_products

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ProductsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"products": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"product_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Product name",
							MarkdownDescription: "Product name",
						},
						"product_version": schema.StringAttribute{
							Computed:            true,
							Description:         "Product version",
							MarkdownDescription: "Product version",
						},
					},
					CustomType: ProductsType{
						ObjectType: types.ObjectType{
							AttrTypes: ProductsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "List of products information",
				MarkdownDescription: "List of products information",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region in which to obtain the Data platform client. If omitted, the `region` argument of the provider is used. Changing this creates a new resource.",
				MarkdownDescription: "The region in which to obtain the Data platform client. If omitted, the `region` argument of the provider is used. Changing this creates a new resource.",
			},
		},
	}
}

type ProductsModel struct {
	Products types.List   `tfsdk:"products"`
	Region   types.String `tfsdk:"region"`
}

var _ basetypes.ObjectTypable = ProductsType{}

type ProductsType struct {
	basetypes.ObjectType
}

func (t ProductsType) Equal(o attr.Type) bool {
	other, ok := o.(ProductsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ProductsType) String() string {
	return "ProductsType"
}

func (t ProductsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	productNameAttribute, ok := attributes["product_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_name is missing from object`)

		return nil, diags
	}

	productNameVal, ok := productNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_name expected to be basetypes.StringValue, was: %T`, productNameAttribute))
	}

	productVersionAttribute, ok := attributes["product_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_version is missing from object`)

		return nil, diags
	}

	productVersionVal, ok := productVersionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_version expected to be basetypes.StringValue, was: %T`, productVersionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ProductsValue{
		ProductName:    productNameVal,
		ProductVersion: productVersionVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewProductsValueNull() ProductsValue {
	return ProductsValue{
		state: attr.ValueStateNull,
	}
}

func NewProductsValueUnknown() ProductsValue {
	return ProductsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewProductsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ProductsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ProductsValue Attribute Value",
				"While creating a ProductsValue value, a missing attribute value was detected. "+
					"A ProductsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProductsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ProductsValue Attribute Type",
				"While creating a ProductsValue value, an invalid attribute value was detected. "+
					"A ProductsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProductsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ProductsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ProductsValue Attribute Value",
				"While creating a ProductsValue value, an extra attribute value was detected. "+
					"A ProductsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ProductsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewProductsValueUnknown(), diags
	}

	productNameAttribute, ok := attributes["product_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_name is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	productNameVal, ok := productNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_name expected to be basetypes.StringValue, was: %T`, productNameAttribute))
	}

	productVersionAttribute, ok := attributes["product_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_version is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	productVersionVal, ok := productVersionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_version expected to be basetypes.StringValue, was: %T`, productVersionAttribute))
	}

	if diags.HasError() {
		return NewProductsValueUnknown(), diags
	}

	return ProductsValue{
		ProductName:    productNameVal,
		ProductVersion: productVersionVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewProductsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ProductsValue {
	object, diags := NewProductsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewProductsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ProductsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewProductsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewProductsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewProductsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewProductsValueMust(ProductsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ProductsType) ValueType(ctx context.Context) attr.Value {
	return ProductsValue{}
}

var _ basetypes.ObjectValuable = ProductsValue{}

type ProductsValue struct {
	ProductName    basetypes.StringValue `tfsdk:"product_name"`
	ProductVersion basetypes.StringValue `tfsdk:"product_version"`
	state          attr.ValueState
}

func (v ProductsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["product_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["product_version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ProductName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["product_name"] = val

		val, err = v.ProductVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["product_version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ProductsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ProductsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ProductsValue) String() string {
	return "ProductsValue"
}

func (v ProductsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"product_name":    basetypes.StringType{},
		"product_version": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"product_name":    v.ProductName,
			"product_version": v.ProductVersion,
		})

	return objVal, diags
}

func (v ProductsValue) Equal(o attr.Value) bool {
	other, ok := o.(ProductsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ProductName.Equal(other.ProductName) {
		return false
	}

	if !v.ProductVersion.Equal(other.ProductVersion) {
		return false
	}

	return true
}

func (v ProductsValue) Type(ctx context.Context) attr.Type {
	return ProductsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ProductsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"product_name":    basetypes.StringType{},
		"product_version": basetypes.StringType{},
	}
}
