// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_kubernetes_cluster_v2

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/vk-cs/terraform-provider-vkcs/vkcs/kubernetes/plan_modifiers"
	"github.com/vk-cs/terraform-provider-vkcs/vkcs/kubernetes/schema_validators"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func KubernetesClusterV2ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_address": schema.StringAttribute{
				Computed:            true,
				Description:         "The URL of the Kubernetes API server.",
				MarkdownDescription: "The URL of the Kubernetes API server.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"api_lb_fip": schema.StringAttribute{
				Computed:            true,
				Description:         "The floating IP of the API load balancer (present if `public_ip` = `true`).",
				MarkdownDescription: "The floating IP of the API load balancer (present if `public_ip` = `true`).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"api_lb_vip": schema.StringAttribute{
				Computed:            true,
				Description:         "The internal VIP of the API load balancer.",
				MarkdownDescription: "The internal VIP of the API load balancer.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"availability_zones": schema.SetAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "A set of availability zones for the cluster's masters. For a `standard` cluster, provide 1, 3, or 5 zones. For a `regional` cluster, provide 3 or 5 zones. **Forces replacement** on change.",
				MarkdownDescription: "A set of availability zones for the cluster's masters. For a `standard` cluster, provide 1, 3, or 5 zones. For a `regional` cluster, provide 3 or 5 zones. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.RequiresReplace(),
				},
				Validators: []validator.Set{
					setvalidator.SizeAtLeast(1),
					setvalidator.ValueStringsAre(stringvalidator.LengthAtLeast(1)),
				},
			},
			"cluster_type": schema.StringAttribute{
				Required:            true,
				Description:         " Either `standard` (single AZ) or `regional` (three AZs). **Forces replacement** on change.",
				MarkdownDescription: " Either `standard` (single AZ) or `regional` (three AZs). **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("standard", "regional"),
				},
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The timestamp when the cluster was created (ISO 8601 format).",
				MarkdownDescription: "The timestamp when the cluster was created (ISO 8601 format).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A human-readable description of the cluster. **Forces replacement** on change. The maximum length is 256 characters.",
				MarkdownDescription: "A human-readable description of the cluster. **Forces replacement** on change. The maximum length is 256 characters.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthAtMost(256),
				},
				Default: stringdefault.StaticString(""),
			},
			"external_network_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the external network for internet access. If omitted, the system selects one automatically. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the external network for internet access. If omitted, the system selects one automatically. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.UUIDValidator{},
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the cluster.",
				MarkdownDescription: "The unique identifier of the cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"insecure_registries": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "A set of registry addresses (e.g., `myregistry.com`) that can be accessed without TLS verification. **Forces replacement** on change.",
				MarkdownDescription: "A set of registry addresses (e.g., `myregistry.com`) that can be accessed without TLS verification. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
					setplanmodifier.RequiresReplace(),
				},
				Validators: []validator.Set{
					setvalidator.ValueStringsAre(schema_validators.InsecureRegistryValidator{}),
				},
			},
			"k8s_config": schema.StringAttribute{
				Computed:            true,
				Description:         "The kubeconfig file contents. **Sensitive** — store securely.",
				MarkdownDescription: "The kubeconfig file contents. **Sensitive** — store securely.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"labels": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "A map of Kubernetes labels to apply to the cluster. Keys and values must conform to Kubernetes label syntax. **Forces replacement** on change.",
				MarkdownDescription: "A map of Kubernetes labels to apply to the cluster. Keys and values must conform to Kubernetes label syntax. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
					mapplanmodifier.RequiresReplace(),
				},
				Validators: []validator.Map{
					schema_validators.KubernetesClusterLabelsValidator{},
				},
			},
			"loadbalancer_allowed_cidrs": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "A set of CIDR blocks permitted to access the API load balancer. If empty, all IPs are allowed. **Forces replacement** on change.",
				MarkdownDescription: "A set of CIDR blocks permitted to access the API load balancer. If empty, all IPs are allowed. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
					setplanmodifier.RequiresReplace(),
				},
				Validators: []validator.Set{
					setvalidator.ValueStringsAre(schema_validators.LbAllowedCIDRValidator{}),
				},
			},
			"loadbalancer_subnet_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the subnet where LoadBalancer services will be allocated IPs. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the subnet where LoadBalancer services will be allocated IPs. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.UUIDValidator{},
				},
			},
			"master_count": schema.Int64Attribute{
				Required:            true,
				Description:         "The number of master nodes. Must be an odd number to maintain etcd quorum (1, 3, or 5). **Forces replacement** on change.",
				MarkdownDescription: "The number of master nodes. Must be an odd number to maintain etcd quorum (1, 3, or 5). **Forces replacement** on change.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"master_disks": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"size": schema.Int64Attribute{
							Computed:            true,
							Description:         "The size of the disk in GB.",
							MarkdownDescription: "The size of the disk in GB.",
						},
						"type": schema.StringAttribute{
							Computed:            true,
							Description:         "The storage volume type provisioned for this master disk component.",
							MarkdownDescription: "The storage volume type provisioned for this master disk component.",
						},
					},
					CustomType: MasterDisksType{
						ObjectType: types.ObjectType{
							AttrTypes: MasterDisksValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "Information about the master node disks. Each disk includes `type` and `size`.",
				MarkdownDescription: "Information about the master node disks. Each disk includes `type` and `size`.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
			},
			"master_flavor": schema.StringAttribute{
				Required:            true,
				Description:         "The flavor ID for master nodes. Changing this triggers a rolling upgrade of the control plane.",
				MarkdownDescription: "The flavor ID for master nodes. Changing this triggers a rolling upgrade of the control plane.",
				Validators: []validator.String{
					schema_validators.UUIDValidator{},
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A unique cluster name. Must be 3-25 lowercase alphanumeric characters or hyphens, start/end with alphanumeric, and contain no consecutive hyphens. Forces replacement on change.",
				MarkdownDescription: "A unique cluster name. Must be 3-25 lowercase alphanumeric characters or hyphens, start/end with alphanumeric, and contain no consecutive hyphens. Forces replacement on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.ClusterNameValidator{},
				},
			},
			"network_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the VPC network where the cluster will be deployed. The network must use the `sprut` SDN. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the VPC network where the cluster will be deployed. The network must use the `sprut` SDN. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.UUIDValidator{},
				},
			},
			"network_plugin": schema.StringAttribute{
				Required:            true,
				Description:         "The CNI plugin to use. Currently only `calico` is supported. **Forces replacement** on change.",
				MarkdownDescription: "The CNI plugin to use. Currently only `calico` is supported. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("calico"),
				},
			},
			"node_groups": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"availability_zone": schema.StringAttribute{
							Computed:            true,
							Description:         "The AZ where the node group resides.",
							MarkdownDescription: "The AZ where the node group resides.",
						},
						"flavor": schema.StringAttribute{
							Computed:            true,
							Description:         "The flavor ID used for the worker nodes.",
							MarkdownDescription: "The flavor ID used for the worker nodes.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The ID of the node group.",
							MarkdownDescription: "The ID of the node group.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "The name of the node group.",
							MarkdownDescription: "The name of the node group.",
						},
						"node_count": schema.Int64Attribute{
							Computed:            true,
							Description:         "The current number of nodes in the group.",
							MarkdownDescription: "The current number of nodes in the group.",
						},
					},
					CustomType: NodeGroupsType{
						ObjectType: types.ObjectType{
							AttrTypes: NodeGroupsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A list of node groups associated with the cluster. Each object contains `id`, `name`, `flavor`, `node_count`, and `availability_zone`.",
				MarkdownDescription: "A list of node groups associated with the cluster. Each object contains `id`, `name`, `flavor`, `node_count`, and `availability_zone`.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
			},
			"pods_ipv4_cidr": schema.StringAttribute{
				Required:            true,
				Description:         "The IPv4 CIDR block for the pod network. Must be a valid private CIDR (e.g., `10.100.0.0/16`). **Forces replacement** on change.",
				MarkdownDescription: "The IPv4 CIDR block for the pod network. Must be a valid private CIDR (e.g., `10.100.0.0/16`). **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.CIDRValidator{},
				},
			},
			"project_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The project ID that owns the cluster.",
				MarkdownDescription: "The project ID that owns the cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"public_ip": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, a floating IP is assigned to the API endpoint. `Forces replacement` on change. Default is `false`.",
				MarkdownDescription: "If `true`, a floating IP is assigned to the API endpoint. `Forces replacement` on change. Default is `false`.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
				Default: booldefault.StaticBool(false),
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region in which to create the cluster. If omitted, the provider's `region` is used. **Forces replacement** on change.",
				MarkdownDescription: "The region in which to create the cluster. If omitted, the provider's `region` is used. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The current cluster status (e.g., `RUNNING`, `RECONCILING`).",
				MarkdownDescription: "The current cluster status (e.g., `RUNNING`, `RECONCILING`).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"subnet_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the subnet for cluster nodes. **Forces replacement** on change.",
				MarkdownDescription: "The ID of the subnet for cluster nodes. **Forces replacement** on change.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.UUIDValidator{},
				},
			},
			"timeouts": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"create": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Timeout for create operation (e.g., `60m`, `2h`). Default is `60m`.",
						MarkdownDescription: "Timeout for create operation (e.g., `60m`, `2h`). Default is `60m`.",
						Validators: []validator.String{
							schema_validators.TimeoutValidator{},
						},
					},
					"delete": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Timeout for delete operation (e.g., `30m`, `1h`). Default is `30m`.",
						MarkdownDescription: "Timeout for delete operation (e.g., `30m`, `1h`). Default is `30m`.",
						Validators: []validator.String{
							schema_validators.TimeoutValidator{},
						},
					},
					"update": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Timeout for update operation (e.g., `120m`, `3h`). Default is `60m`.",
						MarkdownDescription: "Timeout for update operation (e.g., `120m`, `3h`). Default is `60m`.",
						Validators: []validator.String{
							schema_validators.TimeoutValidator{},
						},
					},
				},
				CustomType: TimeoutsType{
					ObjectType: types.ObjectType{
						AttrTypes: TimeoutsValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Timeouts configuration for create, update and delete operations.",
				MarkdownDescription: "Timeouts configuration for create, update and delete operations.",
			},
			"uuid": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The cluster UUID. Can be specified; if not, it is generated automatically. **Changing this forces a new cluster.**",
				MarkdownDescription: "The cluster UUID. Can be specified; if not, it is generated automatically. **Changing this forces a new cluster.**",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					schema_validators.UUIDValidator{},
				},
			},
			"version": schema.StringAttribute{
				Required:            true,
				Description:         "The Kubernetes version to deploy. Only upgrades to a higher version are allowed.",
				MarkdownDescription: "The Kubernetes version to deploy. Only upgrades to a higher version are allowed.",
				PlanModifiers: []planmodifier.String{
					plan_modifiers.AllowOnlyUpgrade(),
				},
				Validators: []validator.String{
					schema_validators.KubernetesVersionValidator{},
				},
			},
		},
	}
}

type KubernetesClusterV2Model struct {
	ApiAddress               types.String  `tfsdk:"api_address"`
	ApiLbFip                 types.String  `tfsdk:"api_lb_fip"`
	ApiLbVip                 types.String  `tfsdk:"api_lb_vip"`
	AvailabilityZones        types.Set     `tfsdk:"availability_zones"`
	ClusterType              types.String  `tfsdk:"cluster_type"`
	CreatedAt                types.String  `tfsdk:"created_at"`
	Description              types.String  `tfsdk:"description"`
	ExternalNetworkId        types.String  `tfsdk:"external_network_id"`
	Id                       types.String  `tfsdk:"id"`
	InsecureRegistries       types.Set     `tfsdk:"insecure_registries"`
	K8sConfig                types.String  `tfsdk:"k8s_config"`
	Labels                   types.Map     `tfsdk:"labels"`
	LoadbalancerAllowedCidrs types.Set     `tfsdk:"loadbalancer_allowed_cidrs"`
	LoadbalancerSubnetId     types.String  `tfsdk:"loadbalancer_subnet_id"`
	MasterCount              types.Int64   `tfsdk:"master_count"`
	MasterDisks              types.Set     `tfsdk:"master_disks"`
	MasterFlavor             types.String  `tfsdk:"master_flavor"`
	Name                     types.String  `tfsdk:"name"`
	NetworkId                types.String  `tfsdk:"network_id"`
	NetworkPlugin            types.String  `tfsdk:"network_plugin"`
	NodeGroups               types.Set     `tfsdk:"node_groups"`
	PodsIpv4Cidr             types.String  `tfsdk:"pods_ipv4_cidr"`
	ProjectId                types.String  `tfsdk:"project_id"`
	PublicIp                 types.Bool    `tfsdk:"public_ip"`
	Region                   types.String  `tfsdk:"region"`
	Status                   types.String  `tfsdk:"status"`
	SubnetId                 types.String  `tfsdk:"subnet_id"`
	Timeouts                 TimeoutsValue `tfsdk:"timeouts"`
	Uuid                     types.String  `tfsdk:"uuid"`
	Version                  types.String  `tfsdk:"version"`
}

var _ basetypes.ObjectTypable = MasterDisksType{}

type MasterDisksType struct {
	basetypes.ObjectType
}

func (t MasterDisksType) Equal(o attr.Type) bool {
	other, ok := o.(MasterDisksType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MasterDisksType) String() string {
	return "MasterDisksType"
}

func (t MasterDisksType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`)

		return nil, diags
	}

	sizeVal, ok := sizeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be basetypes.Int64Value, was: %T`, sizeAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MasterDisksValue{
		Size:            sizeVal,
		MasterDisksType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewMasterDisksValueNull() MasterDisksValue {
	return MasterDisksValue{
		state: attr.ValueStateNull,
	}
}

func NewMasterDisksValueUnknown() MasterDisksValue {
	return MasterDisksValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMasterDisksValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MasterDisksValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MasterDisksValue Attribute Value",
				"While creating a MasterDisksValue value, a missing attribute value was detected. "+
					"A MasterDisksValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MasterDisksValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MasterDisksValue Attribute Type",
				"While creating a MasterDisksValue value, an invalid attribute value was detected. "+
					"A MasterDisksValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MasterDisksValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MasterDisksValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MasterDisksValue Attribute Value",
				"While creating a MasterDisksValue value, an extra attribute value was detected. "+
					"A MasterDisksValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MasterDisksValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMasterDisksValueUnknown(), diags
	}

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`)

		return NewMasterDisksValueUnknown(), diags
	}

	sizeVal, ok := sizeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be basetypes.Int64Value, was: %T`, sizeAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewMasterDisksValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewMasterDisksValueUnknown(), diags
	}

	return MasterDisksValue{
		Size:            sizeVal,
		MasterDisksType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewMasterDisksValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MasterDisksValue {
	object, diags := NewMasterDisksValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMasterDisksValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MasterDisksType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMasterDisksValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMasterDisksValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMasterDisksValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMasterDisksValueMust(MasterDisksValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MasterDisksType) ValueType(ctx context.Context) attr.Value {
	return MasterDisksValue{}
}

var _ basetypes.ObjectValuable = MasterDisksValue{}

type MasterDisksValue struct {
	Size            basetypes.Int64Value  `tfsdk:"size"`
	MasterDisksType basetypes.StringValue `tfsdk:"type"`
	state           attr.ValueState
}

func (v MasterDisksValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["size"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Size.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size"] = val

		val, err = v.MasterDisksType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MasterDisksValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MasterDisksValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MasterDisksValue) String() string {
	return "MasterDisksValue"
}

func (v MasterDisksValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"size": basetypes.Int64Type{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"size": v.Size,
			"type": v.MasterDisksType,
		})

	return objVal, diags
}

func (v MasterDisksValue) Equal(o attr.Value) bool {
	other, ok := o.(MasterDisksValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Size.Equal(other.Size) {
		return false
	}

	if !v.MasterDisksType.Equal(other.MasterDisksType) {
		return false
	}

	return true
}

func (v MasterDisksValue) Type(ctx context.Context) attr.Type {
	return MasterDisksType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MasterDisksValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"size": basetypes.Int64Type{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = NodeGroupsType{}

type NodeGroupsType struct {
	basetypes.ObjectType
}

func (t NodeGroupsType) Equal(o attr.Type) bool {
	other, ok := o.(NodeGroupsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NodeGroupsType) String() string {
	return "NodeGroupsType"
}

func (t NodeGroupsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	availabilityZoneAttribute, ok := attributes["availability_zone"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`availability_zone is missing from object`)

		return nil, diags
	}

	availabilityZoneVal, ok := availabilityZoneAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`availability_zone expected to be basetypes.StringValue, was: %T`, availabilityZoneAttribute))
	}

	flavorAttribute, ok := attributes["flavor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`flavor is missing from object`)

		return nil, diags
	}

	flavorVal, ok := flavorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`flavor expected to be basetypes.StringValue, was: %T`, flavorAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	nodeCountAttribute, ok := attributes["node_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_count is missing from object`)

		return nil, diags
	}

	nodeCountVal, ok := nodeCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_count expected to be basetypes.Int64Value, was: %T`, nodeCountAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NodeGroupsValue{
		AvailabilityZone: availabilityZoneVal,
		Flavor:           flavorVal,
		Id:               idVal,
		Name:             nameVal,
		NodeCount:        nodeCountVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewNodeGroupsValueNull() NodeGroupsValue {
	return NodeGroupsValue{
		state: attr.ValueStateNull,
	}
}

func NewNodeGroupsValueUnknown() NodeGroupsValue {
	return NodeGroupsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNodeGroupsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NodeGroupsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NodeGroupsValue Attribute Value",
				"While creating a NodeGroupsValue value, a missing attribute value was detected. "+
					"A NodeGroupsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodeGroupsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NodeGroupsValue Attribute Type",
				"While creating a NodeGroupsValue value, an invalid attribute value was detected. "+
					"A NodeGroupsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodeGroupsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NodeGroupsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NodeGroupsValue Attribute Value",
				"While creating a NodeGroupsValue value, an extra attribute value was detected. "+
					"A NodeGroupsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NodeGroupsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNodeGroupsValueUnknown(), diags
	}

	availabilityZoneAttribute, ok := attributes["availability_zone"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`availability_zone is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	availabilityZoneVal, ok := availabilityZoneAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`availability_zone expected to be basetypes.StringValue, was: %T`, availabilityZoneAttribute))
	}

	flavorAttribute, ok := attributes["flavor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`flavor is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	flavorVal, ok := flavorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`flavor expected to be basetypes.StringValue, was: %T`, flavorAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	nodeCountAttribute, ok := attributes["node_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_count is missing from object`)

		return NewNodeGroupsValueUnknown(), diags
	}

	nodeCountVal, ok := nodeCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_count expected to be basetypes.Int64Value, was: %T`, nodeCountAttribute))
	}

	if diags.HasError() {
		return NewNodeGroupsValueUnknown(), diags
	}

	return NodeGroupsValue{
		AvailabilityZone: availabilityZoneVal,
		Flavor:           flavorVal,
		Id:               idVal,
		Name:             nameVal,
		NodeCount:        nodeCountVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewNodeGroupsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NodeGroupsValue {
	object, diags := NewNodeGroupsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNodeGroupsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NodeGroupsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNodeGroupsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNodeGroupsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNodeGroupsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNodeGroupsValueMust(NodeGroupsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NodeGroupsType) ValueType(ctx context.Context) attr.Value {
	return NodeGroupsValue{}
}

var _ basetypes.ObjectValuable = NodeGroupsValue{}

type NodeGroupsValue struct {
	AvailabilityZone basetypes.StringValue `tfsdk:"availability_zone"`
	Flavor           basetypes.StringValue `tfsdk:"flavor"`
	Id               basetypes.StringValue `tfsdk:"id"`
	Name             basetypes.StringValue `tfsdk:"name"`
	NodeCount        basetypes.Int64Value  `tfsdk:"node_count"`
	state            attr.ValueState
}

func (v NodeGroupsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["availability_zone"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["flavor"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["node_count"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.AvailabilityZone.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["availability_zone"] = val

		val, err = v.Flavor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["flavor"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.NodeCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["node_count"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NodeGroupsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NodeGroupsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NodeGroupsValue) String() string {
	return "NodeGroupsValue"
}

func (v NodeGroupsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"availability_zone": basetypes.StringType{},
		"flavor":            basetypes.StringType{},
		"id":                basetypes.StringType{},
		"name":              basetypes.StringType{},
		"node_count":        basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"availability_zone": v.AvailabilityZone,
			"flavor":            v.Flavor,
			"id":                v.Id,
			"name":              v.Name,
			"node_count":        v.NodeCount,
		})

	return objVal, diags
}

func (v NodeGroupsValue) Equal(o attr.Value) bool {
	other, ok := o.(NodeGroupsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AvailabilityZone.Equal(other.AvailabilityZone) {
		return false
	}

	if !v.Flavor.Equal(other.Flavor) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.NodeCount.Equal(other.NodeCount) {
		return false
	}

	return true
}

func (v NodeGroupsValue) Type(ctx context.Context) attr.Type {
	return NodeGroupsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NodeGroupsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"availability_zone": basetypes.StringType{},
		"flavor":            basetypes.StringType{},
		"id":                basetypes.StringType{},
		"name":              basetypes.StringType{},
		"node_count":        basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = TimeoutsType{}

type TimeoutsType struct {
	basetypes.ObjectType
}

func (t TimeoutsType) Equal(o attr.Type) bool {
	other, ok := o.(TimeoutsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TimeoutsType) String() string {
	return "TimeoutsType"
}

func (t TimeoutsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createAttribute, ok := attributes["create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`create is missing from object`)

		return nil, diags
	}

	createVal, ok := createAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`create expected to be basetypes.StringValue, was: %T`, createAttribute))
	}

	deleteAttribute, ok := attributes["delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delete is missing from object`)

		return nil, diags
	}

	deleteVal, ok := deleteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delete expected to be basetypes.StringValue, was: %T`, deleteAttribute))
	}

	updateAttribute, ok := attributes["update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`update is missing from object`)

		return nil, diags
	}

	updateVal, ok := updateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`update expected to be basetypes.StringValue, was: %T`, updateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TimeoutsValue{
		Create: createVal,
		Delete: deleteVal,
		Update: updateVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTimeoutsValueNull() TimeoutsValue {
	return TimeoutsValue{
		state: attr.ValueStateNull,
	}
}

func NewTimeoutsValueUnknown() TimeoutsValue {
	return TimeoutsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTimeoutsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TimeoutsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TimeoutsValue Attribute Value",
				"While creating a TimeoutsValue value, a missing attribute value was detected. "+
					"A TimeoutsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TimeoutsValue Attribute Type",
				"While creating a TimeoutsValue value, an invalid attribute value was detected. "+
					"A TimeoutsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TimeoutsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TimeoutsValue Attribute Value",
				"While creating a TimeoutsValue value, an extra attribute value was detected. "+
					"A TimeoutsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TimeoutsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTimeoutsValueUnknown(), diags
	}

	createAttribute, ok := attributes["create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`create is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	createVal, ok := createAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`create expected to be basetypes.StringValue, was: %T`, createAttribute))
	}

	deleteAttribute, ok := attributes["delete"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delete is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	deleteVal, ok := deleteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delete expected to be basetypes.StringValue, was: %T`, deleteAttribute))
	}

	updateAttribute, ok := attributes["update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`update is missing from object`)

		return NewTimeoutsValueUnknown(), diags
	}

	updateVal, ok := updateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`update expected to be basetypes.StringValue, was: %T`, updateAttribute))
	}

	if diags.HasError() {
		return NewTimeoutsValueUnknown(), diags
	}

	return TimeoutsValue{
		Create: createVal,
		Delete: deleteVal,
		Update: updateVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTimeoutsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TimeoutsValue {
	object, diags := NewTimeoutsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTimeoutsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TimeoutsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTimeoutsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTimeoutsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTimeoutsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTimeoutsValueMust(TimeoutsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TimeoutsType) ValueType(ctx context.Context) attr.Value {
	return TimeoutsValue{}
}

var _ basetypes.ObjectValuable = TimeoutsValue{}

type TimeoutsValue struct {
	Create basetypes.StringValue `tfsdk:"create"`
	Delete basetypes.StringValue `tfsdk:"delete"`
	Update basetypes.StringValue `tfsdk:"update"`
	state  attr.ValueState
}

func (v TimeoutsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["create"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["delete"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["update"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Create.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["create"] = val

		val, err = v.Delete.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["delete"] = val

		val, err = v.Update.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["update"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TimeoutsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TimeoutsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TimeoutsValue) String() string {
	return "TimeoutsValue"
}

func (v TimeoutsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"create": basetypes.StringType{},
		"delete": basetypes.StringType{},
		"update": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"create": v.Create,
			"delete": v.Delete,
			"update": v.Update,
		})

	return objVal, diags
}

func (v TimeoutsValue) Equal(o attr.Value) bool {
	other, ok := o.(TimeoutsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Create.Equal(other.Create) {
		return false
	}

	if !v.Delete.Equal(other.Delete) {
		return false
	}

	if !v.Update.Equal(other.Update) {
		return false
	}

	return true
}

func (v TimeoutsValue) Type(ctx context.Context) attr.Type {
	return TimeoutsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TimeoutsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"create": basetypes.StringType{},
		"delete": basetypes.StringType{},
		"update": basetypes.StringType{},
	}
}
