// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_vkcs

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func VkcsProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type VkcsModel struct {
}
