// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_kubernetes_versions_v2

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KubernetesVersionsV2DataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "A synthetic identifier set to \"kubernetes_versions\". This data source does not have a natural ID.",
				MarkdownDescription: "A synthetic identifier set to \"kubernetes_versions\". This data source does not have a natural ID.",
			},
			"k8s_versions": schema.SetAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "A set of available Kubernetes version strings (e.g., [\"v1.33.3\", \"v1.34.2\"]).",
				MarkdownDescription: "A set of available Kubernetes version strings (e.g., [\"v1.33.3\", \"v1.34.2\"]).",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The region for which to retrieve available versions. Defaults to provider's `region`.",
				MarkdownDescription: "The region for which to retrieve available versions. Defaults to provider's `region`.",
			},
		},
	}
}

type KubernetesVersionsV2Model struct {
	Id          types.String `tfsdk:"id"`
	K8sVersions types.Set    `tfsdk:"k8s_versions"`
	Region      types.String `tfsdk:"region"`
}
