name: Check CHANGELOG has been changed
on:
  pull_request:
    paths:
      - 'vkcs/**'
      - '!vkcs/**_test.go'
jobs:
  error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v41
        id: changelog
        with:
          files: |
            CHANGELOG.md
      - name: raise-error
        if: steps.changelog.outputs.any_changed == 'false'
        run: "false"
        shell: bash
